<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20151212173315.1"><vh>@settings</vh>
<v t="leo.20151212173315.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20151212173315.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20160921213353.1"><vh>2016fall 簡報與網誌樣板系統</vh></v>
<v t="amd.20160106095324.1" a="E"><vh>@path ./../</vh>
<v t="leo.20151213173830.1" a="E"><vh>假如要在近端檢視, 使用下列按鈕</vh>
<v t="leo.20161118111218.1"><vh>@button https server</vh></v>
<v t="leo.20151213085727.1"><vh>@button pelican-blog</vh></v>
</v>
<v t="amd.20151215180106.1" a="E"><vh>設定與開發</vh>
<v t="leo.20161013190948.1"><vh>@@edit index.html</vh></v>
<v t="leo.20161014111031.1"><vh>@clean index.html</vh>
<v t="leo.20161014111031.2" a="E"><vh>html</vh>
<v t="leo.20161014111031.3"><vh>head</vh></v>
<v t="leo.20161014111031.4" a="E"><vh>body</vh>
<v t="leo.20161014111031.5" a="E"><vh>reveal div</vh>
<v t="leo.20161014111031.6" a="E"><vh>slides div</vh>
<v t="leo.20161014111031.7" a="E"><vh>封面投影片</vh>
<v t="leo.20161014111031.8"><vh>封面投影片內容</vh></v>
</v>
<v t="leo.20161014111031.9"><vh>20160916W1</vh>
<v t="leo.20161104010025.1"><vh>上課日期</vh>
<v t="leo.20161104010025.2"><vh>20160916</vh></v>
</v>
<v t="leo.20161014111031.10"><vh>上課內容1</vh>
<v t="leo.20161014111031.11"><vh>中秋連假</vh></v>
</v>
</v>
<v t="leo.20161014111031.24"><vh>20160923W2</vh>
<v t="leo.20161104010248.1"><vh>上課日期</vh>
<v t="leo.20161104010248.2"><vh>20160923</vh></v>
</v>
<v t="leo.20161014111031.25"><vh>上課內容1</vh>
<v t="leo.20161014111031.26"><vh>建立40423226.github.io名稱的倉儲</vh></v>
</v>
<v t="leo.20161014111031.27"><vh>上課內容2</vh>
<v t="leo.20161014111031.28"><vh>把分支的預設值改為gh-pages</vh></v>
</v>
</v>
<v t="leo.20161014111031.37"><vh>20160930W3</vh>
<v t="leo.20161104010457.1"><vh>上課日期</vh>
<v t="leo.20161104010457.2"><vh>20160930</vh></v>
</v>
<v t="leo.20161014111031.38"><vh>上課內容1</vh>
<v t="leo.20161014111031.39"><vh>複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
</v>
<v t="leo.20161104010537.1"><vh>上課內容2</vh>
<v t="leo.20161104010537.2"><vh>更改2016fallcadp_hw的README.md檔案</vh></v>
</v>
</v>
<v t="leo.20161014111031.40"><vh>20161007W4</vh>
<v t="leo.20161104010854.1"><vh>上課日期</vh>
<v t="leo.20161104010854.2"><vh>20161007</vh></v>
</v>
<v t="leo.20161014111031.41"><vh>上課內容1</vh>
<v t="leo.20161014111031.42"><vh>設定使用者資料,讓可攜程式更方便</vh></v>
</v>
<v t="leo.20161014111031.43"><vh>上課內容2</vh>
<v t="leo.20161014111031.44"><vh>用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
</v>
</v>
<v t="leo.20161103232830.1"><vh>20161014W5</vh>
<v t="leo.20161104011343.1"><vh>上課日期</vh>
<v t="leo.20161104011343.2"><vh>20161014</vh></v>
</v>
<v t="leo.20161103232830.2"><vh>上課內容1</vh>
<v t="leo.20161103232830.3"><vh>初步認識SolveSpace</vh></v>
</v>
</v>
<v t="leo.20161103232832.1"><vh>20161021W6</vh>
<v t="leo.20161104011407.1"><vh>上課日期</vh>
<v t="leo.20161104011407.2"><vh>20161021</vh></v>
</v>
<v t="leo.20161103232832.2"><vh>上課內容1</vh>
<v t="leo.20161103232832.3"><vh>解決子模組在對應上的問題</vh></v>
</v>
</v>
<v t="leo.20161103233616.1"><vh>20161028W7</vh>
<v t="leo.20161104011701.1"><vh>上課日期</vh>
<v t="leo.20161104011701.2"><vh>20161028</vh></v>
</v>
<v t="leo.20161103233616.2"><vh>上課內容1</vh>
<v t="leo.20161103233616.3"><vh>使用Trace Point計算路徑</vh></v>
</v>
</v>
<v t="leo.20161104203720.1"><vh>20161104W8</vh>
<v t="leo.20161104203720.2"><vh>上課日期</vh>
<v t="leo.20161104203720.3"><vh>20161104</vh></v>
</v>
<v t="leo.20161104203720.4"><vh>上課內容1</vh>
<v t="leo.20161104203720.5"><vh>期中課程評量</vh></v>
</v>
</v>
<v t="leo.20161115000909.1"><vh>20161111W9</vh>
<v t="leo.20161115000909.2"><vh>上課日期</vh>
<v t="leo.20161115000909.3"><vh>20161118</vh></v>
</v>
<v t="leo.20161115000909.4"><vh>上課內容1</vh>
<v t="leo.20161115000909.5"><vh>期中自我評分</vh></v>
</v>
</v>
<v t="leo.20161124210839.1"><vh>20161118W10</vh>
<v t="leo.20161124210839.2"><vh>上課日期</vh>
<v t="leo.20161124210839.3"><vh>20161118</vh></v>
</v>
<v t="leo.20161124210839.4"><vh>上課內容1</vh>
<v t="leo.20161124210839.5"><vh>Solvespace 平面四連桿機構模擬</vh></v>
</v>
</v>
<v t="leo.20161124210841.1"><vh>20161125W11</vh>
<v t="leo.20161124210841.2"><vh>上課日期</vh>
<v t="leo.20161124210841.3"><vh>20161125</vh></v>
</v>
<v t="leo.20161124210841.4"><vh>上課內容1</vh>
<v t="leo.20161124210841.5"><vh>校慶</vh></v>
</v>
</v>
<v t="leo.20161209165346.1"><vh>20161202W12</vh>
<v t="leo.20161209165346.2"><vh>上課日期</vh>
<v t="leo.20161209165346.3"><vh>20161202</vh></v>
</v>
<v t="leo.20161209174033.1"><vh>上課內容1</vh>
<v t="leo.20161209174033.2"><vh>利用SolveSpace存html檔</vh></v>
</v>
<v t="leo.20161209165346.4"><vh>上課內容2</vh>
<v t="leo.20161209165346.5"><vh>SolveSpace_Cube</vh></v>
</v>
<v t="leo.20161209165937.1"><vh>上課內容3</vh>
<v t="leo.20161209165937.2"><vh>SolveSpace_Strut</vh></v>
</v>
<v t="leo.20161209165942.1"><vh>上課內容4</vh>
<v t="leo.20161209165942.2"><vh>SolveSpace_Combination</vh></v>
</v>
</v>
<v t="leo.20161209165348.1"><vh>20161209W13</vh>
<v t="leo.20161209165348.2"><vh>上課日期</vh>
<v t="leo.20161209165348.3"><vh>20161209</vh></v>
</v>
<v t="leo.20161209165348.4"><vh>上課內容1</vh>
<v t="leo.20161209165348.5"><vh>遠端網誌無法更新</vh></v>
</v>
</v>
<v t="leo.20170101215257.1"><vh>20161216W14</vh>
<v t="leo.20170101215257.2"><vh>上課日期</vh>
<v t="leo.20170101215257.3"><vh>20161216</vh></v>
</v>
<v t="leo.20170101215257.4"><vh>上課內容1</vh>
<v t="leo.20170101215257.5"><vh>delta_printer_v2</vh></v>
</v>
</v>
<v t="leo.20170101215259.1"><vh>20161223W15</vh>
<v t="leo.20170101215259.2"><vh>上課日期</vh>
<v t="leo.20170101215259.3"><vh>20161223</vh></v>
</v>
<v t="leo.20170101215259.4"><vh>上課內容1</vh>
<v t="leo.20170101215259.5"><vh>整理目前為止上課的內容</vh></v>
</v>
</v>
<v t="leo.20170101215301.1"><vh>20161230W16</vh>
<v t="leo.20170101215301.2"><vh>上課日期</vh>
<v t="leo.20170101215301.3"><vh>20161230</vh></v>
</v>
<v t="leo.20170101215301.4"><vh>上課內容1</vh>
<v t="leo.20170101215301.5"><vh>繪製 Mechanism Tutorial</vh></v>
</v>
</v>
<v t="leo.20170112140710.1"><vh>20170106W17</vh>
<v t="leo.20170112140710.2"><vh>上課日期</vh>
<v t="leo.20170112140710.3"><vh>20170106</vh></v>
</v>
<v t="leo.20170112140710.4"><vh>上課內容1</vh>
<v t="leo.20170112140710.5"><vh>相對運動練習</vh></v>
</v>
</v>
<v t="leo.20170113103445.1"><vh>20170113W18</vh>
<v t="leo.20170113103445.2"><vh>上課日期</vh>
<v t="leo.20170113103445.3"><vh>20170113</vh></v>
</v>
<v t="leo.20170113103445.4"><vh>上課內容1</vh>
<v t="leo.20170113103445.5"><vh>期末自評總結</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20151213230723.1"><vh>Pelican 設定</vh>
<v t="leo.20151213230957.1"><vh>文章 Date 設定</vh></v>
<v t="leo.20151213230729.1"><vh>使用 summary plugin</vh></v>
</v>
<v t="amd.20151215170117.1"><vh>以下 pelicanconf.py 為近端與遠端的共同設定</vh></v>
<v t="leo.20151212173725.1"><vh>@edit pelicanconf.py</vh></v>
<v t="amd.20151215170221.1"><vh>以下 local_publishconf.py 為近端所使用的設定</vh></v>
<v t="leo.20151213085752.1"><vh>@edit local_publishconf.py</vh></v>
</v>
</v>
<v t="amd.20151215170350.1"><vh>以下為 content 目錄中的 md 檔案</vh></v>
<v t="amd.20151216001126.1"><vh>md 檔案範例</vh></v>
<v t="amd.20151215170031.1" a="E"><vh>@path ./../content</vh>
<v t="amd.20160106093454.1" a="E"><vh>yen 所寫的網誌文章</vh>
<v t="amd.20160727114506.1" a="E"><vh>201609</vh>
<v t="leo.20161028152823.1"><vh>@edit 20160916.md</vh></v>
<v t="leo.20161028153027.1"><vh>@edit 20160923.md</vh></v>
<v t="leo.20161028153033.1"><vh>@edit 20161007.md</vh></v>
<v t="leo.20161028153029.1"><vh>@edit 20161014.md</vh></v>
<v t="leo.20161104203621.1"><vh>@edit 20161104.md</vh></v>
<v t="leo.20161115000357.1"><vh>@edit 20161111.md</vh></v>
<v t="leo.20161118112100.1"><vh>@edit 20161118.md</vh></v>
<v t="leo.20161124205906.1"><vh>@edit 20161125.md</vh></v>
<v t="leo.20161209153338.1"><vh>@edit 20161202.md</vh></v>
<v t="leo.20161230112546.1"><vh>@edit 20161230.md</vh></v>
<v t="leo.20170112135759.1"><vh>@edit 20170106.md</vh></v>
<v t="leo.20170113093236.1"><vh>@edit 20170113.md</vh></v>
</v>
</v>
</v>
<v t="amd.20160106094754.1"><vh>@path ./../content/pages</vh>
<v t="amd.20160106094829.1"><vh>yen 所寫的 pages 文章</vh>
<v t="amd.20160106094844.1"><vh>@edit pages_1.md</vh></v>
</v>
</v>
<v t="amd.20161004202833.1"><vh>@edit ../README.md</vh></v>
<v t="leo.20170115114300.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20170115114300.3"><vh>Recovered node "head" from @clean index.html</vh>
<v t="leo.20170115114300.4"><vh>old:head</vh></v>
<v t="leo.20170115114300.5"><vh>new:head</vh></v>
</v>
<v t="leo.20170115114300.6"><vh>Recovered node "body" from @clean index.html</vh>
<v t="leo.20170115114300.7"><vh>old:body</vh></v>
<v t="leo.20170115114300.8"><vh>new:body</vh></v>
</v>
<v t="leo.20170115114300.9"><vh>Recovered node "reveal div" from @clean index.html</vh>
<v t="leo.20170115114300.10"><vh>old:reveal div</vh></v>
<v t="leo.20170115114300.11"><vh>new:reveal div</vh></v>
</v>
<v t="leo.20170115114300.12"><vh>Recovered node "slides div" from @clean index.html</vh>
<v t="leo.20170115114300.13"><vh>old:slides div</vh></v>
<v t="leo.20170115114300.14"><vh>new:slides div</vh></v>
</v>
<v t="leo.20170115114300.15"><vh>Recovered node "封面投影片" from @clean index.html</vh>
<v t="leo.20170115114300.16"><vh>old:封面投影片</vh></v>
<v t="leo.20170115114300.17"><vh>new:封面投影片</vh></v>
</v>
<v t="leo.20170115114300.18"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20170115114300.19"><vh>old:封面投影片內容</vh></v>
<v t="leo.20170115114300.20"><vh>new:封面投影片內容</vh></v>
</v>
<v t="leo.20170115114300.21"><vh>Recovered node "20160916W1" from @clean index.html</vh>
<v t="leo.20170115114300.22"><vh>old:20160916W1</vh></v>
<v t="leo.20170115114300.23"><vh>new:20160916W1</vh></v>
</v>
<v t="leo.20170115114300.24"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.25"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.26"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.27"><vh>Recovered node "20160916" from @clean index.html</vh>
<v t="leo.20170115114300.28"><vh>old:20160916</vh></v>
<v t="leo.20170115114300.29"><vh>new:20160916</vh></v>
</v>
<v t="leo.20170115114300.30"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.31"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.32"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.33"><vh>Recovered node "中秋連假" from @clean index.html</vh>
<v t="leo.20170115114300.34"><vh>old:中秋連假</vh></v>
<v t="leo.20170115114300.35"><vh>new:中秋連假</vh></v>
</v>
<v t="leo.20170115114300.36"><vh>Recovered node "20160923W2" from @clean index.html</vh>
<v t="leo.20170115114300.37"><vh>old:20160923W2</vh></v>
<v t="leo.20170115114300.38"><vh>new:20160923W2</vh></v>
</v>
<v t="leo.20170115114300.39"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.40"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.41"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.42"><vh>Recovered node "20160923" from @clean index.html</vh>
<v t="leo.20170115114300.43"><vh>old:20160923</vh></v>
<v t="leo.20170115114300.44"><vh>new:20160923</vh></v>
</v>
<v t="leo.20170115114300.45"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.46"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.47"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.48"><vh>Recovered node "建立40423226.github.io名稱的倉儲" from @clean index.html</vh>
<v t="leo.20170115114300.49"><vh>old:建立40423226.github.io名稱的倉儲</vh></v>
<v t="leo.20170115114300.50"><vh>new:建立40423226.github.io名稱的倉儲</vh></v>
</v>
<v t="leo.20170115114300.51"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170115114300.52"><vh>old:上課內容2</vh></v>
<v t="leo.20170115114300.53"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170115114300.54"><vh>Recovered node "把分支的預設值改為gh-pages" from @clean index.html</vh>
<v t="leo.20170115114300.55"><vh>old:把分支的預設值改為gh-pages</vh></v>
<v t="leo.20170115114300.56"><vh>new:把分支的預設值改為gh-pages</vh></v>
</v>
<v t="leo.20170115114300.57"><vh>Recovered node "20160930W3" from @clean index.html</vh>
<v t="leo.20170115114300.58"><vh>old:20160930W3</vh></v>
<v t="leo.20170115114300.59"><vh>new:20160930W3</vh></v>
</v>
<v t="leo.20170115114300.60"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.61"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.62"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.63"><vh>Recovered node "20160930" from @clean index.html</vh>
<v t="leo.20170115114300.64"><vh>old:20160930</vh></v>
<v t="leo.20170115114300.65"><vh>new:20160930</vh></v>
</v>
<v t="leo.20170115114300.66"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.67"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.68"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.69"><vh>Recovered node "複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲" from @clean index.html</vh>
<v t="leo.20170115114300.70"><vh>old:複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
<v t="leo.20170115114300.71"><vh>new:複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
</v>
<v t="leo.20170115114300.72"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170115114300.73"><vh>old:上課內容2</vh></v>
<v t="leo.20170115114300.74"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170115114300.75"><vh>Recovered node "更改2016fallcadp_hw的README.md檔案" from @clean index.html</vh>
<v t="leo.20170115114300.76"><vh>old:更改2016fallcadp_hw的README.md檔案</vh></v>
<v t="leo.20170115114300.77"><vh>new:更改2016fallcadp_hw的README.md檔案</vh></v>
</v>
<v t="leo.20170115114300.78"><vh>Recovered node "20161007W4" from @clean index.html</vh>
<v t="leo.20170115114300.79"><vh>old:20161007W4</vh></v>
<v t="leo.20170115114300.80"><vh>new:20161007W4</vh></v>
</v>
<v t="leo.20170115114300.81"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.82"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.83"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.84"><vh>Recovered node "20161007" from @clean index.html</vh>
<v t="leo.20170115114300.85"><vh>old:20161007</vh></v>
<v t="leo.20170115114300.86"><vh>new:20161007</vh></v>
</v>
<v t="leo.20170115114300.87"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.88"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.89"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.90"><vh>Recovered node "設定使用者資料,讓可攜程式更方便" from @clean index.html</vh>
<v t="leo.20170115114300.91"><vh>old:設定使用者資料,讓可攜程式更方便</vh></v>
<v t="leo.20170115114300.92"><vh>new:設定使用者資料,讓可攜程式更方便</vh></v>
</v>
<v t="leo.20170115114300.93"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170115114300.94"><vh>old:上課內容2</vh></v>
<v t="leo.20170115114300.95"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170115114300.96"><vh>Recovered node "用2016fallcadp_bg6的名稱,建立小組倉儲" from @clean index.html</vh>
<v t="leo.20170115114300.97"><vh>old:用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
<v t="leo.20170115114300.98"><vh>new:用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
</v>
<v t="leo.20170115114300.99"><vh>Recovered node "20161014W5" from @clean index.html</vh>
<v t="leo.20170115114300.100"><vh>old:20161014W5</vh></v>
<v t="leo.20170115114300.101"><vh>new:20161014W5</vh></v>
</v>
<v t="leo.20170115114300.102"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.103"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.104"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.105"><vh>Recovered node "20161014" from @clean index.html</vh>
<v t="leo.20170115114300.106"><vh>old:20161014</vh></v>
<v t="leo.20170115114300.107"><vh>new:20161014</vh></v>
</v>
<v t="leo.20170115114300.108"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.109"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.110"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.111"><vh>Recovered node "初步認識SolveSpace" from @clean index.html</vh>
<v t="leo.20170115114300.112"><vh>old:初步認識SolveSpace</vh></v>
<v t="leo.20170115114300.113"><vh>new:初步認識SolveSpace</vh></v>
</v>
<v t="leo.20170115114300.114"><vh>Recovered node "20161021W6" from @clean index.html</vh>
<v t="leo.20170115114300.115"><vh>old:20161021W6</vh></v>
<v t="leo.20170115114300.116"><vh>new:20161021W6</vh></v>
</v>
<v t="leo.20170115114300.117"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.118"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.119"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.120"><vh>Recovered node "20161021" from @clean index.html</vh>
<v t="leo.20170115114300.121"><vh>old:20161021</vh></v>
<v t="leo.20170115114300.122"><vh>new:20161021</vh></v>
</v>
<v t="leo.20170115114300.123"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.124"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.125"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.126"><vh>Recovered node "解決子模組在對應上的問題" from @clean index.html</vh>
<v t="leo.20170115114300.127"><vh>old:解決子模組在對應上的問題</vh></v>
<v t="leo.20170115114300.128"><vh>new:解決子模組在對應上的問題</vh></v>
</v>
<v t="leo.20170115114300.129"><vh>Recovered node "20161028W7" from @clean index.html</vh>
<v t="leo.20170115114300.130"><vh>old:20161028W7</vh></v>
<v t="leo.20170115114300.131"><vh>new:20161028W7</vh></v>
</v>
<v t="leo.20170115114300.132"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.133"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.134"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.135"><vh>Recovered node "20161028" from @clean index.html</vh>
<v t="leo.20170115114300.136"><vh>old:20161028</vh></v>
<v t="leo.20170115114300.137"><vh>new:20161028</vh></v>
</v>
<v t="leo.20170115114300.138"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.139"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.140"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.141"><vh>Recovered node "使用Trace Point計算路徑" from @clean index.html</vh>
<v t="leo.20170115114300.142"><vh>old:使用Trace Point計算路徑</vh></v>
<v t="leo.20170115114300.143"><vh>new:使用Trace Point計算路徑</vh></v>
</v>
<v t="leo.20170115114300.144"><vh>Recovered node "20161104W8" from @clean index.html</vh>
<v t="leo.20170115114300.145"><vh>old:20161104W8</vh></v>
<v t="leo.20170115114300.146"><vh>new:20161104W8</vh></v>
</v>
<v t="leo.20170115114300.147"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.148"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.149"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.150"><vh>Recovered node "20161104" from @clean index.html</vh>
<v t="leo.20170115114300.151"><vh>old:20161104</vh></v>
<v t="leo.20170115114300.152"><vh>new:20161104</vh></v>
</v>
<v t="leo.20170115114300.153"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.154"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.155"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.156"><vh>Recovered node "期中課程評量" from @clean index.html</vh>
<v t="leo.20170115114300.157"><vh>old:期中課程評量</vh></v>
<v t="leo.20170115114300.158"><vh>new:期中課程評量</vh></v>
</v>
<v t="leo.20170115114300.159"><vh>Recovered node "20161111W9" from @clean index.html</vh>
<v t="leo.20170115114300.160"><vh>old:20161111W9</vh></v>
<v t="leo.20170115114300.161"><vh>new:20161111W9</vh></v>
</v>
<v t="leo.20170115114300.162"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.163"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.164"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.165"><vh>Recovered node "20161118" from @clean index.html</vh>
<v t="leo.20170115114300.166"><vh>old:20161118</vh></v>
<v t="leo.20170115114300.167"><vh>new:20161118</vh></v>
</v>
<v t="leo.20170115114300.168"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.169"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.170"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.171"><vh>Recovered node "期中自我評分" from @clean index.html</vh>
<v t="leo.20170115114300.172"><vh>old:期中自我評分</vh></v>
<v t="leo.20170115114300.173"><vh>new:期中自我評分</vh></v>
</v>
<v t="leo.20170115114300.174"><vh>Recovered node "20161118W10" from @clean index.html</vh>
<v t="leo.20170115114300.175"><vh>old:20161118W10</vh></v>
<v t="leo.20170115114300.176"><vh>new:20161118W10</vh></v>
</v>
<v t="leo.20170115114300.177"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.178"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.179"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.180"><vh>Recovered node "20161118" from @clean index.html</vh>
<v t="leo.20170115114300.181"><vh>old:20161118</vh></v>
<v t="leo.20170115114300.182"><vh>new:20161118</vh></v>
</v>
<v t="leo.20170115114300.183"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.184"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.185"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.186"><vh>Recovered node "Solvespace 平面四連桿機構模擬" from @clean index.html</vh>
<v t="leo.20170115114300.187"><vh>old:Solvespace 平面四連桿機構模擬</vh></v>
<v t="leo.20170115114300.188"><vh>new:Solvespace 平面四連桿機構模擬</vh></v>
</v>
<v t="leo.20170115114300.189"><vh>Recovered node "20161125W11" from @clean index.html</vh>
<v t="leo.20170115114300.190"><vh>old:20161125W11</vh></v>
<v t="leo.20170115114300.191"><vh>new:20161125W11</vh></v>
</v>
<v t="leo.20170115114300.192"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.193"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.194"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.195"><vh>Recovered node "20161125" from @clean index.html</vh>
<v t="leo.20170115114300.196"><vh>old:20161125</vh></v>
<v t="leo.20170115114300.197"><vh>new:20161125</vh></v>
</v>
<v t="leo.20170115114300.198"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.199"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.200"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.201"><vh>Recovered node "校慶" from @clean index.html</vh>
<v t="leo.20170115114300.202"><vh>old:校慶</vh></v>
<v t="leo.20170115114300.203"><vh>new:校慶</vh></v>
</v>
<v t="leo.20170115114300.204"><vh>Recovered node "20161202W12" from @clean index.html</vh>
<v t="leo.20170115114300.205"><vh>old:20161202W12</vh></v>
<v t="leo.20170115114300.206"><vh>new:20161202W12</vh></v>
</v>
<v t="leo.20170115114300.207"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.208"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.209"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.210"><vh>Recovered node "20161202" from @clean index.html</vh>
<v t="leo.20170115114300.211"><vh>old:20161202</vh></v>
<v t="leo.20170115114300.212"><vh>new:20161202</vh></v>
</v>
<v t="leo.20170115114300.213"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.214"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.215"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.216"><vh>Recovered node "利用SolveSpace存html檔" from @clean index.html</vh>
<v t="leo.20170115114300.217"><vh>old:利用SolveSpace存html檔</vh></v>
<v t="leo.20170115114300.218"><vh>new:利用SolveSpace存html檔</vh></v>
</v>
<v t="leo.20170115114300.219"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170115114300.220"><vh>old:上課內容2</vh></v>
<v t="leo.20170115114300.221"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170115114300.222"><vh>Recovered node "SolveSpace_Cube" from @clean index.html</vh>
<v t="leo.20170115114300.223"><vh>old:SolveSpace_Cube</vh></v>
<v t="leo.20170115114300.224"><vh>new:SolveSpace_Cube</vh></v>
</v>
<v t="leo.20170115114300.225"><vh>Recovered node "上課內容3" from @clean index.html</vh>
<v t="leo.20170115114300.226"><vh>old:上課內容3</vh></v>
<v t="leo.20170115114300.227"><vh>new:上課內容3</vh></v>
</v>
<v t="leo.20170115114300.228"><vh>Recovered node "SolveSpace_Strut" from @clean index.html</vh>
<v t="leo.20170115114300.229"><vh>old:SolveSpace_Strut</vh></v>
<v t="leo.20170115114300.230"><vh>new:SolveSpace_Strut</vh></v>
</v>
<v t="leo.20170115114300.231"><vh>Recovered node "上課內容4" from @clean index.html</vh>
<v t="leo.20170115114300.232"><vh>old:上課內容4</vh></v>
<v t="leo.20170115114300.233"><vh>new:上課內容4</vh></v>
</v>
<v t="leo.20170115114300.234"><vh>Recovered node "SolveSpace_Combination" from @clean index.html</vh>
<v t="leo.20170115114300.235"><vh>old:SolveSpace_Combination</vh></v>
<v t="leo.20170115114300.236"><vh>new:SolveSpace_Combination</vh></v>
</v>
<v t="leo.20170115114300.237"><vh>Recovered node "20161209W13" from @clean index.html</vh>
<v t="leo.20170115114300.238"><vh>old:20161209W13</vh></v>
<v t="leo.20170115114300.239"><vh>new:20161209W13</vh></v>
</v>
<v t="leo.20170115114300.240"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.241"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.242"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.243"><vh>Recovered node "20161209" from @clean index.html</vh>
<v t="leo.20170115114300.244"><vh>old:20161209</vh></v>
<v t="leo.20170115114300.245"><vh>new:20161209</vh></v>
</v>
<v t="leo.20170115114300.246"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.247"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.248"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.249"><vh>Recovered node "遠端網誌無法更新" from @clean index.html</vh>
<v t="leo.20170115114300.250"><vh>old:遠端網誌無法更新</vh></v>
<v t="leo.20170115114300.251"><vh>new:遠端網誌無法更新</vh></v>
</v>
<v t="leo.20170115114300.252"><vh>Recovered node "20161216W14" from @clean index.html</vh>
<v t="leo.20170115114300.253"><vh>old:20161216W14</vh></v>
<v t="leo.20170115114300.254"><vh>new:20161216W14</vh></v>
</v>
<v t="leo.20170115114300.255"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.256"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.257"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.258"><vh>Recovered node "20161216" from @clean index.html</vh>
<v t="leo.20170115114300.259"><vh>old:20161216</vh></v>
<v t="leo.20170115114300.260"><vh>new:20161216</vh></v>
</v>
<v t="leo.20170115114300.261"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.262"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.263"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.264"><vh>Recovered node "delta_printer_v2" from @clean index.html</vh>
<v t="leo.20170115114300.265"><vh>old:delta_printer_v2</vh></v>
<v t="leo.20170115114300.266"><vh>new:delta_printer_v2</vh></v>
</v>
<v t="leo.20170115114300.267"><vh>Recovered node "20161223W15" from @clean index.html</vh>
<v t="leo.20170115114300.268"><vh>old:20161223W15</vh></v>
<v t="leo.20170115114300.269"><vh>new:20161223W15</vh></v>
</v>
<v t="leo.20170115114300.270"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.271"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.272"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.273"><vh>Recovered node "20161223" from @clean index.html</vh>
<v t="leo.20170115114300.274"><vh>old:20161223</vh></v>
<v t="leo.20170115114300.275"><vh>new:20161223</vh></v>
</v>
<v t="leo.20170115114300.276"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.277"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.278"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.279"><vh>Recovered node "整理目前為止上課的內容" from @clean index.html</vh>
<v t="leo.20170115114300.280"><vh>old:整理目前為止上課的內容</vh></v>
<v t="leo.20170115114300.281"><vh>new:整理目前為止上課的內容</vh></v>
</v>
<v t="leo.20170115114300.282"><vh>Recovered node "20161230W16" from @clean index.html</vh>
<v t="leo.20170115114300.283"><vh>old:20161230W16</vh></v>
<v t="leo.20170115114300.284"><vh>new:20161230W16</vh></v>
</v>
<v t="leo.20170115114300.285"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.286"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.287"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.288"><vh>Recovered node "20161230" from @clean index.html</vh>
<v t="leo.20170115114300.289"><vh>old:20161230</vh></v>
<v t="leo.20170115114300.290"><vh>new:20161230</vh></v>
</v>
<v t="leo.20170115114300.291"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.292"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.293"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.294"><vh>Recovered node "繪製 Mechanism Tutorial" from @clean index.html</vh>
<v t="leo.20170115114300.295"><vh>old:繪製 Mechanism Tutorial</vh></v>
<v t="leo.20170115114300.296"><vh>new:繪製 Mechanism Tutorial</vh></v>
</v>
<v t="leo.20170115114300.297"><vh>Recovered node "20170106W17" from @clean index.html</vh>
<v t="leo.20170115114300.298"><vh>old:20170106W17</vh></v>
<v t="leo.20170115114300.299"><vh>new:20170106W17</vh></v>
</v>
<v t="leo.20170115114300.300"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.301"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.302"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.303"><vh>Recovered node "20170106" from @clean index.html</vh>
<v t="leo.20170115114300.304"><vh>old:20170106</vh></v>
<v t="leo.20170115114300.305"><vh>new:20170106</vh></v>
</v>
<v t="leo.20170115114300.306"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.307"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.308"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.309"><vh>Recovered node "相對運動練習" from @clean index.html</vh>
<v t="leo.20170115114300.310"><vh>old:相對運動練習</vh></v>
<v t="leo.20170115114300.311"><vh>new:相對運動練習</vh></v>
</v>
<v t="leo.20170115114300.312"><vh>Recovered node "20170113W18" from @clean index.html</vh>
<v t="leo.20170115114300.313"><vh>old:20170113W18</vh></v>
<v t="leo.20170115114300.314"><vh>new:20170113W18</vh></v>
</v>
<v t="leo.20170115114300.315"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170115114300.316"><vh>old:上課日期</vh></v>
<v t="leo.20170115114300.317"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170115114300.318"><vh>Recovered node "20170113" from @clean index.html</vh>
<v t="leo.20170115114300.319"><vh>old:20170113</vh></v>
<v t="leo.20170115114300.320"><vh>new:20170113</vh></v>
</v>
<v t="leo.20170115114300.321"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170115114300.322"><vh>old:上課內容1</vh></v>
<v t="leo.20170115114300.323"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170115114300.324"><vh>Recovered node "期末自評總結" from @clean index.html</vh>
<v t="leo.20170115114300.325"><vh>old:期末自評總結</vh></v>
<v t="leo.20170115114300.326"><vh>new:期末自評總結</vh></v>
</v>
</v>
<v t="leo.20170116002413.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20170116002413.3"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20170116002413.4"><vh>old:封面投影片內容</vh></v>
<v t="leo.20170116002413.5"><vh>new:封面投影片內容</vh></v>
</v>
<v t="leo.20170116002413.6"><vh>Recovered node "20160916W1" from @clean index.html</vh>
<v t="leo.20170116002413.7"><vh>old:20160916W1</vh></v>
<v t="leo.20170116002413.8"><vh>new:20160916W1</vh></v>
</v>
<v t="leo.20170116002413.9"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.10"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.11"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.12"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.13"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.14"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.15"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.16"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.17"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.18"><vh>Recovered node "20160930W3" from @clean index.html</vh>
<v t="leo.20170116002413.19"><vh>old:20160930W3</vh></v>
<v t="leo.20170116002413.20"><vh>new:20160930W3</vh></v>
</v>
<v t="leo.20170116002413.21"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.22"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.23"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.24"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.25"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.26"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.27"><vh>Recovered node "複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲" from @clean index.html</vh>
<v t="leo.20170116002413.28"><vh>old:複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
<v t="leo.20170116002413.29"><vh>new:複製網誌和簡報的設定檔到2016fallcadp_hw的倉儲</vh></v>
</v>
<v t="leo.20170116002413.30"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170116002413.31"><vh>old:上課內容2</vh></v>
<v t="leo.20170116002413.32"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170116002413.33"><vh>Recovered node "更改2016fallcadp_hw的README.md檔案" from @clean index.html</vh>
<v t="leo.20170116002413.34"><vh>old:更改2016fallcadp_hw的README.md檔案</vh></v>
<v t="leo.20170116002413.35"><vh>new:更改2016fallcadp_hw的README.md檔案</vh></v>
</v>
<v t="leo.20170116002413.36"><vh>Recovered node "20161007W4" from @clean index.html</vh>
<v t="leo.20170116002413.37"><vh>old:20161007W4</vh></v>
<v t="leo.20170116002413.38"><vh>new:20161007W4</vh></v>
</v>
<v t="leo.20170116002413.39"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.40"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.41"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.42"><vh>Recovered node "20161007" from @clean index.html</vh>
<v t="leo.20170116002413.43"><vh>old:20161007</vh></v>
<v t="leo.20170116002413.44"><vh>new:20161007</vh></v>
</v>
<v t="leo.20170116002413.45"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.46"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.47"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.48"><vh>Recovered node "設定使用者資料,讓可攜程式更方便" from @clean index.html</vh>
<v t="leo.20170116002413.49"><vh>old:設定使用者資料,讓可攜程式更方便</vh></v>
<v t="leo.20170116002413.50"><vh>new:設定使用者資料,讓可攜程式更方便</vh></v>
</v>
<v t="leo.20170116002413.51"><vh>Recovered node "上課內容2" from @clean index.html</vh>
<v t="leo.20170116002413.52"><vh>old:上課內容2</vh></v>
<v t="leo.20170116002413.53"><vh>new:上課內容2</vh></v>
</v>
<v t="leo.20170116002413.54"><vh>Recovered node "用2016fallcadp_bg6的名稱,建立小組倉儲" from @clean index.html</vh>
<v t="leo.20170116002413.55"><vh>old:用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
<v t="leo.20170116002413.56"><vh>new:用2016fallcadp_bg6的名稱,建立小組倉儲</vh></v>
</v>
<v t="leo.20170116002413.57"><vh>Recovered node "20161014W5" from @clean index.html</vh>
<v t="leo.20170116002413.58"><vh>old:20161014W5</vh></v>
<v t="leo.20170116002413.59"><vh>new:20161014W5</vh></v>
</v>
<v t="leo.20170116002413.60"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.61"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.62"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.63"><vh>Recovered node "20161014" from @clean index.html</vh>
<v t="leo.20170116002413.64"><vh>old:20161014</vh></v>
<v t="leo.20170116002413.65"><vh>new:20161014</vh></v>
</v>
<v t="leo.20170116002413.66"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.67"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.68"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.69"><vh>Recovered node "初步認識SolveSpace" from @clean index.html</vh>
<v t="leo.20170116002413.70"><vh>old:初步認識SolveSpace</vh></v>
<v t="leo.20170116002413.71"><vh>new:初步認識SolveSpace</vh></v>
</v>
<v t="leo.20170116002413.72"><vh>Recovered node "20161021W6" from @clean index.html</vh>
<v t="leo.20170116002413.73"><vh>old:20161021W6</vh></v>
<v t="leo.20170116002413.74"><vh>new:20161021W6</vh></v>
</v>
<v t="leo.20170116002413.75"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.76"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.77"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.78"><vh>Recovered node "20161021" from @clean index.html</vh>
<v t="leo.20170116002413.79"><vh>old:20161021</vh></v>
<v t="leo.20170116002413.80"><vh>new:20161021</vh></v>
</v>
<v t="leo.20170116002413.81"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.82"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.83"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.84"><vh>Recovered node "解決子模組在對應上的問題" from @clean index.html</vh>
<v t="leo.20170116002413.85"><vh>old:解決子模組在對應上的問題</vh></v>
<v t="leo.20170116002413.86"><vh>new:解決子模組在對應上的問題</vh></v>
</v>
<v t="leo.20170116002413.87"><vh>Recovered node "20161028W7" from @clean index.html</vh>
<v t="leo.20170116002413.88"><vh>old:20161028W7</vh></v>
<v t="leo.20170116002413.89"><vh>new:20161028W7</vh></v>
</v>
<v t="leo.20170116002413.90"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.91"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.92"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.93"><vh>Recovered node "20161028" from @clean index.html</vh>
<v t="leo.20170116002413.94"><vh>old:20161028</vh></v>
<v t="leo.20170116002413.95"><vh>new:20161028</vh></v>
</v>
<v t="leo.20170116002413.96"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.97"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.98"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.99"><vh>Recovered node "使用Trace Point計算路徑" from @clean index.html</vh>
<v t="leo.20170116002413.100"><vh>old:使用Trace Point計算路徑</vh></v>
<v t="leo.20170116002413.101"><vh>new:使用Trace Point計算路徑</vh></v>
</v>
<v t="leo.20170116002413.102"><vh>Recovered node "20161104W8" from @clean index.html</vh>
<v t="leo.20170116002413.103"><vh>old:20161104W8</vh></v>
<v t="leo.20170116002413.104"><vh>new:20161104W8</vh></v>
</v>
<v t="leo.20170116002413.105"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.106"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.107"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.108"><vh>Recovered node "20161104" from @clean index.html</vh>
<v t="leo.20170116002413.109"><vh>old:20161104</vh></v>
<v t="leo.20170116002413.110"><vh>new:20161104</vh></v>
</v>
<v t="leo.20170116002413.111"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.112"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.113"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.114"><vh>Recovered node "期中課程評量" from @clean index.html</vh>
<v t="leo.20170116002413.115"><vh>old:期中課程評量</vh></v>
<v t="leo.20170116002413.116"><vh>new:期中課程評量</vh></v>
</v>
<v t="leo.20170116002413.117"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.118"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.119"><vh>new:上課日期</vh></v>
</v>
<v t="leo.20170116002413.120"><vh>Recovered node "上課內容1" from @clean index.html</vh>
<v t="leo.20170116002413.121"><vh>old:上課內容1</vh></v>
<v t="leo.20170116002413.122"><vh>new:上課內容1</vh></v>
</v>
<v t="leo.20170116002413.123"><vh>Recovered node "期中自我評分" from @clean index.html</vh>
<v t="leo.20170116002413.124"><vh>old:期中自我評分</vh></v>
<v t="leo.20170116002413.125"><vh>new:期中自我評分</vh></v>
</v>
<v t="leo.20170116002413.126"><vh>Recovered node "上課日期" from @clean index.html</vh>
<v t="leo.20170116002413.127"><vh>old:上課日期</vh></v>
<v t="leo.20170116002413.128"><vh>new:上課日期</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20151215170031.1"></t>
<t tx="amd.20151215170117.1"></t>
<t tx="amd.20151215170221.1"></t>
<t tx="amd.20151215170350.1"></t>
<t tx="amd.20151215180106.1"></t>
<t tx="amd.20151216001126.1">@language md
Title: 文章標題 (請注意各文章的標題不可相同, 比較保險的作法是冠上四個學號尾碼)
Date: 2016-09-2 12:00
Category: 類別
Tags: 標籤
Author: yen

這裡放入文章摘要

&lt;!-- PELICAN_END_SUMMARY --&gt;

這裡為文章主要內容

程式碼

&lt;pre class="brush: python;"&gt;
print("hello")
&lt;/pre&gt;</t>
<t tx="amd.20160106093454.1"></t>
<t tx="amd.20160106094754.1"></t>
<t tx="amd.20160106094829.1"></t>
<t tx="amd.20160106095324.1"></t>
<t tx="amd.20160727114506.1"></t>
<t tx="amd.20160921213353.1"></t>
<t tx="leo.20151212173315.1"></t>
<t tx="leo.20151212173315.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20151212173315.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20151213085727.1">@language python
import os
#os.system("pelican content -o output -s local_publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican content -o blog -s local_publishconf.py")
g.es("admin pelican 近端執行完畢")


</t>
<t tx="leo.20151213173830.1"></t>
<t tx="leo.20151213230723.1"></t>
<t tx="leo.20151213230729.1">利用

&lt;!-- PELICAN_END_SUMMARY --&gt;

來界定 Summary 摘要內容

前提, 必須設定 

PLUGIN_PATHS = ['plugin']

與

PLUGINS = ['liquid_tags.notebook', 'summary']

並且從 https://github.com/getpelican/pelican-plugins

取得 summary plugin</t>
<t tx="leo.20151213230957.1"># 設定網誌以 md 檔案建立的 file system date 為準, 無需自行設定

DEFAULT_DATE = 'fs'</t>
<t tx="leo.20161013190948.1">@language html
&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;title&gt;
redirecting ....
&lt;/title&gt;
&lt;head&gt;
&lt;meta http-equiv="refresh" content="0; url=https://mdecourse.github.io/2016fallcadpa/" /&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;/body&gt;
&lt;/html&gt;</t>
<t tx="leo.20161014111031.1">@language xml
@tabwidth -4
@others
</t>
<t tx="leo.20161014111031.10">                               &lt;section&gt;
					&lt;h2&gt;這一次的作業我拍好影片,但是我借用德威的VIMEO上傳的時候德威忘記登出所以就直接借用他的了,我們這組是一起討論後最後才成功畫出作品的,很喜歡團隊合作的感覺,蠻有成就感的雖然在畫的時候失敗了一次又一次哈哈&lt;/h2&gt;
@others
                              
				&lt;!-- Example of nested vertical slides --&gt;
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業2&lt;/p&gt;
</t>
<t tx="leo.20161014111031.11">				
                              &lt;/section&gt;
</t>
<t tx="leo.20161014111031.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;
</t>
<t tx="leo.20161014111031.24">				
@others
				&lt;/section&gt;
</t>
<t tx="leo.20161014111031.25">						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
@others
				&lt;section&gt;
			
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;在試用了老師所介紹的兩套軟體-SolveSpace 和 Onshape後 覺得Onshape較SolveSpace好用，而Onshape和我們常用的soildwork還滿像的 所以用起來比較習慣。SolveSpace沒一些快速指令，每執行完一項功能，就要重新點選，覺得比較麻煩一點!!&lt;/p&gt;
						
</t>
<t tx="leo.20161014111031.26">						&lt;a href="#/2"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20161014111031.27">					
					&lt;/section&gt;
@others
						&lt;p&gt;第二週 1.radinsed半徑 2.diameter直徑 3.place放置 4.symmetrically對稱 5.lnitially開始 6.oriented定位 7.axes軸 8.indicated表示 9.respectively分別 10.parallel平行 11.extruding長出 12.automatically自動 13.coincident一模一樣 14.constraint約束 15.horizontal橫 16.perpendicular垂直 17.step圖(格式)
                                                &lt;p&gt;錄影工具:sharex 1.paths 2.task → screen recorder → options 開始錄製:shift+ print screen 射出成型軟體:moldex3d
                                                &lt;p&gt;作業 成品影片:https://vimeo.com/185115914
					&lt;/p&gt;
					
</t>
<t tx="leo.20161014111031.28">
				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
</t>
<t tx="leo.20161014111031.3">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;
</t>
<t tx="leo.20161014111031.37">
@others
</t>
<t tx="leo.20161014111031.38">@others
					&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/JFKJpplaqDs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161014111031.39">				
				
				&lt;section&gt;
</t>
<t tx="leo.20161014111031.4">
@others
</t>
<t tx="leo.20161014111031.40">@others
</t>
<t tx="leo.20161014111031.41">@others
</t>
<t tx="leo.20161014111031.42"></t>
<t tx="leo.20161014111031.43">@others
</t>
<t tx="leo.20161014111031.44"></t>
<t tx="leo.20161014111031.5">	&lt;body&gt;
@others
</t>
<t tx="leo.20161014111031.6">
		&lt;div class="reveal"&gt;
@others
</t>
<t tx="leo.20161014111031.7">
			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
@others
				
				&lt;section&gt;
				&lt;p&gt;筆記:1.創2016fallcadp_hw 將README打勾 格式:python 加密:agpl 新增gh-pages分支 進入setting 點branches 將master變更為gh-pages 點update 
					2.git clone 2016fallcadp_hw cd 2016fallcadp_hw git branch git checkout gh-pages git branch(再次檢查) 
					3.創 學號.github.io 將README打勾 格式:python 加密:agpl 點選create new file 打入index.html 點commit new file
</t>
<t tx="leo.20161014111031.8">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40423201 黃上芸 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;
</t>
<t tx="leo.20161014111031.9">					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
@others
					&lt;iframe src="https://player.vimeo.com/video/190123005" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161103232830.1">@others
</t>
<t tx="leo.20161103232830.2">@others
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/QPBiOIqfW28" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161103232830.3">				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20161103232832.1">@others
				&lt;/div&gt;
</t>
<t tx="leo.20161103232832.2">@others
				&lt;section&gt;
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;這一次我們這組整個討論下來,覺得這一次的作業比較複雜一點但,在這一次又有學到新的知識,又得到了一些還沒學過的能力&lt;p&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20161103232832.3">				&lt;/section&gt;

</t>
<t tx="leo.20161103233616.1">@others
</t>
<t tx="leo.20161103233616.2">@others
</t>
<t tx="leo.20161103233616.3"></t>
<t tx="leo.20161104010025.1"> &lt;/p&gt;
				&lt;/section&gt;
@others
					&lt;h4&gt;作業1&lt;/h4&gt;
					&lt;iframe src="https://player.vimeo.com/video/185818182" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
			
                              &lt;/section&gt;
				
</t>
<t tx="leo.20161104010025.2">		
                               &lt;section&gt;
</t>
<t tx="leo.20161104010248.1">						
					
@others
					&lt;section&gt;
				
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
</t>
<t tx="leo.20161104010248.2">					&lt;/section&gt;
					
</t>
<t tx="leo.20161104010457.1">				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
@others
  &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
				
				&lt;/section&gt;

</t>
<t tx="leo.20161104010457.2">			
  &lt;p&gt;第三週 proxy設定:proxy.mde.tw 通訊阜:3128 去聲音指令:ffmpeg.exe -i 檔名 -c copy -an out.mp4 字幕指令:ffmpeg.exe -i out.mp4 -vf subtitles=in.srt out2.mp4 安裝pelican指令:pip install pelican
</t>
<t tx="leo.20161104010537.1">@others
</t>
<t tx="leo.20161104010537.2"></t>
<t tx="leo.20161104010854.1">@others
</t>
<t tx="leo.20161104010854.2"></t>
<t tx="leo.20161104011343.1">@others
</t>
<t tx="leo.20161104011343.2"></t>
<t tx="leo.20161104011407.1">@others
</t>
<t tx="leo.20161104011407.2"></t>
<t tx="leo.20161104011701.1">@others
</t>
<t tx="leo.20161104011701.2"></t>
<t tx="leo.20161104203720.1">@others
</t>
<t tx="leo.20161104203720.2">@others
</t>
<t tx="leo.20161104203720.3"></t>
<t tx="leo.20161104203720.4">@others
</t>
<t tx="leo.20161104203720.5"></t>
<t tx="leo.20161115000909.1">
@others
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20161115000909.2">		&lt;/div&gt;

@others

		&lt;script&gt;
			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
</t>
<t tx="leo.20161115000909.3">		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
</t>
<t tx="leo.20161115000909.4">				controls: true,
				progress: true,
@others
				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20161115000909.5">				history: true,
				center: true,
				transition: 'slide', // none/fade/slide/convex/concave/zoom
</t>
<t tx="leo.20161118111218.1">@language python
import os
import subprocess
import threading
import http.server, ssl

def domake():
    # build directory
    os.chdir("./../")
    server_address = ('localhost', 8443)
    httpd = http.server.HTTPServer(server_address, http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket(httpd.socket,
                                   server_side=True,
                                   certfile='localhost.crt',
                                   keyfile='localhost.key',
                                   ssl_version=ssl.PROTOCOL_TLSv1)
    print("8443 https server started")
    httpd.serve_forever()

# 利用執行緒執行 https 伺服器
make = threading.Thread(target=domake)
make.start()</t>
<t tx="leo.20161124210839.1">					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
@others
</t>
<t tx="leo.20161124210839.2">					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
@others
		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20161124210839.3">				]
			});
</t>
<t tx="leo.20161124210839.4">@others
</t>
<t tx="leo.20161124210839.5"></t>
<t tx="leo.20161124210841.1">@others
</t>
<t tx="leo.20161124210841.2">@others
</t>
<t tx="leo.20161124210841.3"></t>
<t tx="leo.20161124210841.4">@others
</t>
<t tx="leo.20161124210841.5"></t>
<t tx="leo.20161209165346.1">@others
</t>
<t tx="leo.20161209165346.2">@others
</t>
<t tx="leo.20161209165346.3"></t>
<t tx="leo.20161209165346.4">@others
</t>
<t tx="leo.20161209165346.5"></t>
<t tx="leo.20161209165348.1">@others
</t>
<t tx="leo.20161209165348.2">@others
</t>
<t tx="leo.20161209165348.3"></t>
<t tx="leo.20161209165348.4">@others
</t>
<t tx="leo.20161209165348.5"></t>
<t tx="leo.20161209165937.1">@others
</t>
<t tx="leo.20161209165937.2"></t>
<t tx="leo.20161209165942.1">@others
</t>
<t tx="leo.20161209165942.2"></t>
<t tx="leo.20161209174033.1">@others
</t>
<t tx="leo.20161209174033.2"></t>
<t tx="leo.20170101215257.1">@others
</t>
<t tx="leo.20170101215257.2">@others
</t>
<t tx="leo.20170101215257.3"></t>
<t tx="leo.20170101215257.4">@others
</t>
<t tx="leo.20170101215257.5"></t>
<t tx="leo.20170101215259.1">@others
</t>
<t tx="leo.20170101215259.2">@others
</t>
<t tx="leo.20170101215259.3"></t>
<t tx="leo.20170101215259.4">@others
</t>
<t tx="leo.20170101215259.5"></t>
<t tx="leo.20170101215301.1">@others
</t>
<t tx="leo.20170101215301.2">@others
</t>
<t tx="leo.20170101215301.3"></t>
<t tx="leo.20170101215301.4">@others
</t>
<t tx="leo.20170101215301.5"></t>
<t tx="leo.20170112140710.1">@others
</t>
<t tx="leo.20170112140710.2">@others
</t>
<t tx="leo.20170112140710.3"></t>
<t tx="leo.20170112140710.4">@others
</t>
<t tx="leo.20170112140710.5"></t>
<t tx="leo.20170113103445.1">@others
</t>
<t tx="leo.20170113103445.2">@others
</t>
<t tx="leo.20170113103445.3"></t>
<t tx="leo.20170113103445.4">@others
</t>
<t tx="leo.20170113103445.5"></t>
<t tx="leo.20170115114300.10">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20170115114300.100">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.101">						
@others
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_IBrCR0BCEs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.102">(uncached) leo.20161104011343.1
Diff...
- 					也
- 					&lt;/section&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
- 			&lt;h2&gt;心得&lt;/h2&gt;
- 				&lt;p&gt;心得:老師這次的作業我們組員都付出了時間和汗水一起完成,我也從其中利用程式增進我不少的繪圖技巧與知識&lt;p&gt;
- 		
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
- 					
+ 						
? +
- 					&lt;/section&gt;
</t>
<t tx="leo.20170115114300.103">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.104">					也
					&lt;/section&gt;
@others
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;心得:老師這次的作業我們組員都付出了時間和汗水一起完成,我也從其中利用程式增進我不少的繪圖技巧與知識&lt;p&gt;
		
					
					&lt;/section&gt;
</t>
<t tx="leo.20170115114300.105">(uncached) leo.20161104011343.2
Diff...
- 					&lt;section&gt;
- 			
+ ## 2016-10-14 第五週
+ 
</t>
<t tx="leo.20170115114300.106">## 2016-10-14 第五週

</t>
<t tx="leo.20170115114300.107">					&lt;section&gt;
			
</t>
<t tx="leo.20170115114300.108">(uncached) leo.20161103232830.2
Diff...
- 					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
- 						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/AdBvhRRuhgU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+     &lt;/script&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
- 				&lt;section&gt;
- 					&lt;p&gt;作業4&lt;/p&gt;
+ 
+ 						
</t>
<t tx="leo.20170115114300.109">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.11">	&lt;body&gt;
@others
</t>
<t tx="leo.20170115114300.110">					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
@others
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/AdBvhRRuhgU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20170115114300.111">(uncached) leo.20161103232830.3
Diff...
+ ## 初步認識SolveSpace
- 					&lt;/section&gt;
- 				&lt;/section&gt;
  
- 				&lt;section&gt;
- 					&lt;p&gt;作業4&lt;/p&gt;
+ &lt;iframe src="https://player.vimeo.com/video/190087085" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170115114300.112">## 初步認識SolveSpace

&lt;iframe src="https://player.vimeo.com/video/190087085" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170115114300.113">					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20170115114300.114">(uncached) leo.20161103232832.1
Diff...
- 				&lt;/section&gt;
? ---- -
+ &lt;section&gt;
  @others
- 				&lt;section&gt;
? ----         -
+ &lt;/section&gt;?  +
</t>
<t tx="leo.20170115114300.115">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.116">				&lt;/section&gt;
@others
				&lt;section&gt;
</t>
<t tx="leo.20170115114300.117">(uncached) leo.20161104011407.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- 				&lt;section&gt;
- @others
- 				&lt;/section&gt;
  
+ 						
- 				&lt;section&gt;
- 					&lt;p&gt;作業4&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/UEyyR0mh9Kk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.118">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.119">
				&lt;section&gt;
@others
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/UEyyR0mh9Kk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.12">(uncached) leo.20161014111031.6
Diff...
+ &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
+ &lt;div class="slides"&gt;
+ @others
+ &lt;/div&gt;
  
- 		&lt;div class="reveal"&gt;
- @others
</t>
<t tx="leo.20170115114300.120">(uncached) leo.20161104011407.2
Diff...
- 			                &lt;p&gt;作業4&lt;/p&gt;
- 			                &lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gun-R6LVY3c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ ## 2016-10-21 第六週
+ 
</t>
<t tx="leo.20170115114300.121">## 2016-10-21 第六週

</t>
<t tx="leo.20170115114300.122">			                &lt;p&gt;作業4&lt;/p&gt;
			                &lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gun-R6LVY3c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.123">(uncached) leo.20161103232832.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
- @others
- 				&lt;section&gt;
- 					&lt;h2&gt;心得&lt;/h2&gt;
- 					&lt;p&gt;老師給我們的零件網站,透過這一次的作業,我發現非常實用,以後應該還會多多利用那個網站,是個非常方便的網站&lt;p&gt;
- 				&lt;/section&gt;
  
+ 						
</t>
<t tx="leo.20170115114300.124">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.125">				&lt;/section&gt;

@others
				&lt;section&gt;
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;老師給我們的零件網站,透過這一次的作業,我發現非常實用,以後應該還會多多利用那個網站,是個非常方便的網站&lt;p&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170115114300.126">(uncached) leo.20161103232832.3
Diff...
+ ## 解決子模組在對應上的問題
- 				&lt;section&gt;
- 					&lt;p&gt;作業4&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/CgB678cjUhI" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				&lt;/section&gt;
  
+ &lt;p&gt;因為之前的2016fallcadp_hw倉儲少複製了一些東西,刪除舊的倉儲後,重新做一個和之前倉儲同名的2016fallcadp_hw倉儲,但是在小組倉儲所連結的子模組,抓不到新倉儲連結,所以我們需要重新加入一次組員倉儲的資料&lt;/p&gt;
+ 
+ 
</t>
<t tx="leo.20170115114300.127">## 解決子模組在對應上的問題

&lt;p&gt;因為之前的2016fallcadp_hw倉儲少複製了一些東西,刪除舊的倉儲後,重新做一個和之前倉儲同名的2016fallcadp_hw倉儲,但是在小組倉儲所連結的子模組,抓不到新倉儲連結,所以我們需要重新加入一次組員倉儲的資料&lt;/p&gt;


</t>
<t tx="leo.20170115114300.128">				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/CgB678cjUhI" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170115114300.129">(uncached) leo.20161103233616.1
Diff...
- 					&lt;p&gt;作業5&lt;/p&gt;
+ &lt;section&gt;
  @others
- 				&lt;/section&gt;
? ----          -
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.13">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="leo.20170115114300.130">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.131">					&lt;p&gt;作業5&lt;/p&gt;
@others
				&lt;/section&gt;
</t>
<t tx="leo.20170115114300.132">(uncached) leo.20161104011701.1
Diff...
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/SWmuThwltWo" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				&lt;/section&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 					&lt;p&gt;作業5&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Vj1Pi6R-Xus" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
- 				&lt;section&gt;
+ 
+ 						
</t>
<t tx="leo.20170115114300.133">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.134">					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/SWmuThwltWo" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;
@others
					&lt;p&gt;作業5&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Vj1Pi6R-Xus" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170115114300.135">(uncached) leo.20161104011701.2
Diff...
+ ## 2016-10-28 第七週
  
- 				&lt;section&gt;
</t>
<t tx="leo.20170115114300.136">## 2016-10-28 第七週

</t>
<t tx="leo.20170115114300.137">
				&lt;section&gt;
</t>
<t tx="leo.20170115114300.138">(uncached) leo.20161103233616.2
Diff...
- 					&lt;p&gt;作業5&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ZZ8DBt7tuYk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
+ 
+ 						
- 				&lt;section&gt;
- 					&lt;p&gt;作業6&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/dktF_l6UY8o" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.139">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.14">
		&lt;div class="reveal"&gt;
@others
</t>
<t tx="leo.20170115114300.140">					&lt;p&gt;作業5&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ZZ8DBt7tuYk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
@others
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業6&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/dktF_l6UY8o" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.141">(uncached) leo.20161103233616.3
Diff...
- 				&lt;/section&gt;
+ ## 使用Trace Point計算路徑
  
- 				&lt;section&gt;
- 					&lt;h2&gt;心得&lt;/h2&gt;
- 					&lt;p&gt;在改尺寸時遇到了一點麻煩,我們在討論是每一個草圖都要改,還是只要去改最外面的輪廓就好,這次作業很有挑戰&lt;p&gt;
+ &lt;iframe src="https://player.vimeo.com/video/190090265" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170115114300.142">## 使用Trace Point計算路徑

&lt;iframe src="https://player.vimeo.com/video/190090265" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170115114300.143">				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;在改尺寸時遇到了一點麻煩,我們在討論是每一個草圖都要改,還是只要去改最外面的輪廓就好,這次作業很有挑戰&lt;p&gt;
</t>
<t tx="leo.20170115114300.144">(uncached) leo.20161104203720.1
Diff...
-                                  &lt;section&gt;
+ &lt;section&gt;
  @others
- 			&lt;/div&gt;
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.145">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.146">                                 &lt;section&gt;
@others
			&lt;/div&gt;
</t>
<t tx="leo.20170115114300.147">(uncached) leo.20161104203720.2
Diff...
- 					&lt;p&gt;作業6&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pCNcDhYsaM8" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 				&lt;section&gt;
- 					&lt;p&gt;作業6&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pIv-YnnAzPE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
+ 
+ 						
</t>
<t tx="leo.20170115114300.148">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.149">					&lt;p&gt;作業6&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pCNcDhYsaM8" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
@others
				&lt;section&gt;
					&lt;p&gt;作業6&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pIv-YnnAzPE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170115114300.15">(uncached) leo.20161014111031.7
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
+ 
- 			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
- @others
- 				
+ 						
? ++
- 				&lt;section&gt;
- 				&lt;p&gt;筆記:1.創2016fallcadp_hw 將README打勾 格式:python 加密:agpl 新增gh-pages分支 進入setting 點branches 將master變更為gh-pages 點update 
- 					2.git clone 2016fallcadp_hw cd 2016fallcadp_hw git branch git checkout gh-pages git branch(再次檢查) 
- 					3.創 學號.github.io 將README打勾 格式:python 加密:agpl 點選create new file 打入index.html 點commit new file
</t>
<t tx="leo.20170115114300.150">(uncached) leo.20161104203720.3
Diff...
- 				&lt;/section&gt;
+ ## 2016-11-04 第八週
  
</t>
<t tx="leo.20170115114300.151">## 2016-11-04 第八週

</t>
<t tx="leo.20170115114300.152">				&lt;/section&gt;

</t>
<t tx="leo.20170115114300.153">(uncached) leo.20161104203720.4
Diff...
- 				&lt;section&gt;
- 					&lt;p&gt;作業6&lt;/p&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 					&lt;h2&gt;心得&lt;/h2&gt;
- 					&lt;p&gt;這一次大家的討論還是非常的熱絡,大家都會去從問題中學到新的知識,也會學習到解決問題的方法,而不是碰到問題就停滯不前了&lt;p&gt;
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
+ 
- 				
+ 						
? ++
</t>
<t tx="leo.20170115114300.154">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.155">				&lt;section&gt;
					&lt;p&gt;作業6&lt;/p&gt;
@others
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;這一次大家的討論還是非常的熱絡,大家都會去從問題中學到新的知識,也會學習到解決問題的方法,而不是碰到問題就停滯不前了&lt;p&gt;
				&lt;/section&gt;

				
</t>
<t tx="leo.20170115114300.156">(uncached) leo.20161104203720.5
Diff...
+ ## 期中課程評分
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/8rT5k7EoovE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				&lt;/section&gt;
  
- 				&lt;section&gt;
+ &lt;p&gt;&lt;a href="http://pygroup-ag100.rhcloud.com"&gt;評分系統&lt;/a&gt;&lt;/p&gt;
+ 
</t>
<t tx="leo.20170115114300.157">## 期中課程評分

&lt;p&gt;&lt;a href="http://pygroup-ag100.rhcloud.com"&gt;評分系統&lt;/a&gt;&lt;/p&gt;

</t>
<t tx="leo.20170115114300.158">					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/8rT5k7EoovE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170115114300.159">(uncached) leo.20161115000909.1
Diff...
- 
+ &lt;section&gt;
  @others
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.16">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.160">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.161">
@others
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20170115114300.162">(uncached) leo.20161115000909.2
Diff...
- 		&lt;/div&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- @others
  
+ 						
- 		&lt;script&gt;
- 
- 			// More info https://github.com/hakimel/reveal.js#configuration
- 			Reveal.initialize({
</t>
<t tx="leo.20170115114300.163">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.164">		&lt;/div&gt;

@others

		&lt;script&gt;

			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
</t>
<t tx="leo.20170115114300.165">(uncached) leo.20161115000909.3
Diff...
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
+ ## 2016-11-18 第九週
+ 
</t>
<t tx="leo.20170115114300.166">## 2016-11-18 第九週

</t>
<t tx="leo.20170115114300.167">		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
</t>
<t tx="leo.20170115114300.168">(uncached) leo.20161115000909.4
Diff...
- 				controls: true,
- 				progress: true,
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
+ 
+ 						
- 				// More info https://github.com/hakimel/reveal.js#dependencies
- 				dependencies: [
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20170115114300.169">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.17">
			&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
@others
				
				&lt;section&gt;
				&lt;p&gt;筆記:1.創2016fallcadp_hw 將README打勾 格式:python 加密:agpl 新增gh-pages分支 進入setting 點branches 將master變更為gh-pages 點update 
					2.git clone 2016fallcadp_hw cd 2016fallcadp_hw git branch git checkout gh-pages git branch(再次檢查) 
					3.創 學號.github.io 將README打勾 格式:python 加密:agpl 點選create new file 打入index.html 點commit new file
</t>
<t tx="leo.20170115114300.170">				controls: true,
				progress: true,
@others

				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20170115114300.171">(uncached) leo.20161115000909.5
Diff...
+ ## 期中自我評分
- 				history: true,
- 				center: true,
  
- 				transition: 'slide', // none/fade/slide/convex/concave/zoom
+ &lt;p&gt;&lt;a href="http://mde.tw/2016fallcadp/blog/2016fall-ji-jie-she-ji-zhu-ti-jiao-xue.html"&gt;檢查自己的連結是否正確&lt;/a&gt;&lt;/p&gt;
+ 
</t>
<t tx="leo.20170115114300.172">## 期中自我評分

&lt;p&gt;&lt;a href="http://mde.tw/2016fallcadp/blog/2016fall-ji-jie-she-ji-zhu-ti-jiao-xue.html"&gt;檢查自己的連結是否正確&lt;/a&gt;&lt;/p&gt;

</t>
<t tx="leo.20170115114300.173">				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom
</t>
<t tx="leo.20170115114300.174">(uncached) leo.20161124210839.1
Diff...
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.175">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.176">					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
@others
</t>
<t tx="leo.20170115114300.177">(uncached) leo.20161124210839.2
Diff...
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
- 					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- 		&lt;/script&gt;
  
- 	&lt;/body&gt;
+ 						
</t>
<t tx="leo.20170115114300.178">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.179">					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
@others

		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20170115114300.18">(uncached) leo.20161014111031.8
Diff...
- 			&lt;div class="slides"&gt;
- 				&lt;section&gt;
- 					&lt;h1&gt;40423203 鄭惟芯 計算機程式課程&lt;/h1&gt;
- 					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
- 					&lt;p&gt;
- 						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
- 					&lt;/p&gt;
-                     &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
- 				&lt;/section&gt;
+ ## 2016Fall 電腦輔助設計實習課程
+ ### 虎科大機械設計工程系
+ ### 設計二乙
+ ### 40423226
+ ### 胡 原 愷
+ 
+ &lt;small&gt;
+ [個人網誌](https://40423226.github.io/2016fallcadp_hw/blog/)
+ &lt;/small&gt;
</t>
<t tx="leo.20170115114300.180">(uncached) leo.20161124210839.3
Diff...
- 				]
- 			});
+ ## 2016-11-18 第十週
+ 
</t>
<t tx="leo.20170115114300.181">## 2016-11-18 第十週

</t>
<t tx="leo.20170115114300.182">				]
			});
</t>
<t tx="leo.20170115114300.183">(uncached) leo.20161124210839.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.184">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.185">@others
</t>
<t tx="leo.20170115114300.186">(uncached) leo.20161124210839.5
Diff...
+ ## Solvespace 平面四連桿機構模擬
+ 
+ &lt;iframe src="https://player.vimeo.com/video/192930481" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
</t>
<t tx="leo.20170115114300.187">## Solvespace 平面四連桿機構模擬

&lt;iframe src="https://player.vimeo.com/video/192930481" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;

</t>
<t tx="leo.20170115114300.188"></t>
<t tx="leo.20170115114300.189">(uncached) leo.20161124210841.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.19">## 2016Fall 電腦輔助設計實習課程
### 虎科大機械設計工程系
### 設計二乙
### 40423226
### 胡 原 愷

&lt;small&gt;
[個人網誌](https://40423226.github.io/2016fallcadp_hw/blog/)
&lt;/small&gt;
</t>
<t tx="leo.20170115114300.190">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.191">@others
</t>
<t tx="leo.20170115114300.192">(uncached) leo.20161124210841.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.193">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.194">@others
</t>
<t tx="leo.20170115114300.195">(uncached) leo.20161124210841.3
Diff...
+ ## 2016-11-25 第十一週
+ 
</t>
<t tx="leo.20170115114300.196">## 2016-11-25 第十一週

</t>
<t tx="leo.20170115114300.197"></t>
<t tx="leo.20170115114300.198">(uncached) leo.20161124210841.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.199">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.2"></t>
<t tx="leo.20170115114300.20">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40423203 鄭惟芯 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;
</t>
<t tx="leo.20170115114300.200">@others
</t>
<t tx="leo.20170115114300.201">(uncached) leo.20161124210841.5
Diff...
+ ## 虎科大36週年校慶</t>
<t tx="leo.20170115114300.202">## 虎科大36週年校慶</t>
<t tx="leo.20170115114300.203"></t>
<t tx="leo.20170115114300.204">(uncached) leo.20161209165346.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.205">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.206">@others
</t>
<t tx="leo.20170115114300.207">(uncached) leo.20161209165346.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.208">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.209">@others
</t>
<t tx="leo.20170115114300.21">(uncached) leo.20161014111031.9
Diff...
- 					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
+ &lt;section&gt;
  @others
- 					&lt;iframe src="https://player.vimeo.com/video/190128689" width="640" height="325" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;/section&gt;
</t>
<t tx="leo.20170115114300.210">(uncached) leo.20161209165346.3
Diff...
+ ## 2016-12-02 第十二週
+ 
</t>
<t tx="leo.20170115114300.211">## 2016-12-02 第十二週

</t>
<t tx="leo.20170115114300.212"></t>
<t tx="leo.20170115114300.213">(uncached) leo.20161209174033.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.214">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.215">@others
</t>
<t tx="leo.20170115114300.216">(uncached) leo.20161209174033.2
Diff...
+ ## 利用SolveSpace存html檔
+ 
+ &lt;iframe src="https://player.vimeo.com/video/194948275" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.217">## 利用SolveSpace存html檔

&lt;iframe src="https://player.vimeo.com/video/194948275" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.218"></t>
<t tx="leo.20170115114300.219">(uncached) leo.20161209165346.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.22">&lt;section&gt;
@others
&lt;/section&gt;
</t>
<t tx="leo.20170115114300.220">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.221">@others
</t>
<t tx="leo.20170115114300.222">(uncached) leo.20161209165346.5
Diff...
+ ## Cube
+ &lt;iframe src="https://player.vimeo.com/video/194943832" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.223">## Cube
&lt;iframe src="https://player.vimeo.com/video/194943832" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.224"></t>
<t tx="leo.20170115114300.225">(uncached) leo.20161209165937.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.226">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.227">@others
</t>
<t tx="leo.20170115114300.228">(uncached) leo.20161209165937.2
Diff...
+ ## Strut
+ 
+ &lt;iframe src="https://player.vimeo.com/video/194943838" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.229">## Strut

&lt;iframe src="https://player.vimeo.com/video/194943838" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.23">					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
@others
					&lt;iframe src="https://player.vimeo.com/video/190128689" width="640" height="325" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.230"></t>
<t tx="leo.20170115114300.231">(uncached) leo.20161209165942.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.232">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.233">@others
</t>
<t tx="leo.20170115114300.234">(uncached) leo.20161209165942.2
Diff...
+ ## 組合
+ 
+ &lt;iframe src="https://player.vimeo.com/video/194943848" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.235">## 組合

&lt;iframe src="https://player.vimeo.com/video/194943848" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.236"></t>
<t tx="leo.20170115114300.237">(uncached) leo.20161209165348.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.238">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.239">@others
</t>
<t tx="leo.20170115114300.24">(uncached) leo.20161104010025.1
Diff...
-  &lt;/p&gt;
- 				&lt;/section&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
- 					&lt;h4&gt;作業1&lt;/h4&gt;
- 					&lt;iframe src="https://player.vimeo.com/video/185824836" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
- 			
-                               &lt;/section&gt;
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
- 				
+ 						
? ++
</t>
<t tx="leo.20170115114300.240">(uncached) leo.20161209165348.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.241">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.242">@others
</t>
<t tx="leo.20170115114300.243">(uncached) leo.20161209165348.3
Diff...
+ ## 2016-12-09 第十三週
+ 
</t>
<t tx="leo.20170115114300.244">## 2016-12-09 第十三週

</t>
<t tx="leo.20170115114300.245"></t>
<t tx="leo.20170115114300.246">(uncached) leo.20161209165348.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.247">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.248">@others
</t>
<t tx="leo.20170115114300.249">(uncached) leo.20161209165348.5
Diff...
+ ## 遠端網誌無法更新
+ 
+ &lt;p&gt;近端利用瀏覽器檢查網誌是正常,但是遠端的網誌卻沒有更新,發現推上去的資料出現問題,GitHub還親自寄信給我&lt;/p&gt;</t>
<t tx="leo.20170115114300.25">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.250">## 遠端網誌無法更新

&lt;p&gt;近端利用瀏覽器檢查網誌是正常,但是遠端的網誌卻沒有更新,發現推上去的資料出現問題,GitHub還親自寄信給我&lt;/p&gt;</t>
<t tx="leo.20170115114300.251"></t>
<t tx="leo.20170115114300.252">(uncached) leo.20170101215257.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.253">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.254">@others
</t>
<t tx="leo.20170115114300.255">(uncached) leo.20170101215257.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.256">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.257">@others
</t>
<t tx="leo.20170115114300.258">(uncached) leo.20170101215257.3
Diff...
+ ## 2016-12-16 第十四週
+ 
</t>
<t tx="leo.20170115114300.259">## 2016-12-16 第十四週

</t>
<t tx="leo.20170115114300.26"> &lt;/p&gt;
				&lt;/section&gt;
@others
					&lt;h4&gt;作業1&lt;/h4&gt;
					&lt;iframe src="https://player.vimeo.com/video/185824836" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
			
                              &lt;/section&gt;
				
</t>
<t tx="leo.20170115114300.260"></t>
<t tx="leo.20170115114300.261">(uncached) leo.20170101215257.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.262">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.263">@others
</t>
<t tx="leo.20170115114300.264">(uncached) leo.20170101215257.5
Diff...
+ ## delta_printer
+ 
+ &lt;img src="data/solvespace/delta_printer_v2/delta_printer.png" width="800" /&gt;</t>
<t tx="leo.20170115114300.265">## delta_printer

&lt;img src="data/solvespace/delta_printer_v2/delta_printer.png" width="800" /&gt;</t>
<t tx="leo.20170115114300.266"></t>
<t tx="leo.20170115114300.267">(uncached) leo.20170101215259.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.268">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.269">@others
</t>
<t tx="leo.20170115114300.27">(uncached) leo.20161104010025.2
Diff...
- 		
-                                &lt;section&gt;
+ ## 2016-09-16 第一週
+ 
</t>
<t tx="leo.20170115114300.270">(uncached) leo.20170101215259.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.271">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.272">@others
</t>
<t tx="leo.20170115114300.273">(uncached) leo.20170101215259.3
Diff...
+ ## 2016-12-23 第十五週
+ 
</t>
<t tx="leo.20170115114300.274">## 2016-12-23 第十五週

</t>
<t tx="leo.20170115114300.275"></t>
<t tx="leo.20170115114300.276">(uncached) leo.20170101215259.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.277">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.278">@others
</t>
<t tx="leo.20170115114300.279">(uncached) leo.20170101215259.5
Diff...
+ ## 整理目前為止上課的內容</t>
<t tx="leo.20170115114300.28">## 2016-09-16 第一週

</t>
<t tx="leo.20170115114300.280">## 整理目前為止上課的內容</t>
<t tx="leo.20170115114300.281"></t>
<t tx="leo.20170115114300.282">(uncached) leo.20170101215301.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.283">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.284">@others
</t>
<t tx="leo.20170115114300.285">(uncached) leo.20170101215301.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.286">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.287">@others
</t>
<t tx="leo.20170115114300.288">(uncached) leo.20170101215301.3
Diff...
+ ## 2016-12-30 第十六週
+ 
</t>
<t tx="leo.20170115114300.289">## 2016-12-30 第十六週

</t>
<t tx="leo.20170115114300.29">		
                               &lt;section&gt;
</t>
<t tx="leo.20170115114300.290"></t>
<t tx="leo.20170115114300.291">(uncached) leo.20170101215301.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.292">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.293">@others
</t>
<t tx="leo.20170115114300.294">(uncached) leo.20170101215301.5
Diff...
+ ## 繪製 Mechanism Tutorial
+ 
+ &lt;img src="data/image/Mechanism Tutorial.png" width="800" /&gt;</t>
<t tx="leo.20170115114300.295">## 繪製 Mechanism Tutorial

&lt;img src="data/image/Mechanism Tutorial.png" width="800" /&gt;</t>
<t tx="leo.20170115114300.296"></t>
<t tx="leo.20170115114300.297">(uncached) leo.20170112140710.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.298">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.299">@others
</t>
<t tx="leo.20170115114300.3">(uncached) leo.20161014111031.3
Diff...
+ &lt;head&gt;
+     &lt;meta charset="utf-8"&gt;
+ &lt;title&gt;
+ 2016 Fall 電腦輔助設計實習課程
+ &lt;/title&gt;
+     &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
+     &lt;meta name="author" content="Hakim El Hattab"&gt;
+     
+     &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
+     &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
+     
+     &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
+     
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
+     
+     &lt;!-- Theme used for syntax highlighting of code --&gt;
+     &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
  
- 	&lt;head&gt;
- 		&lt;meta charset="utf-8"&gt;
+     &lt;!-- Printing and PDF exports --&gt;
+     &lt;script&gt;
+         var link = document.createElement( 'link' );
+         link.rel = 'stylesheet';
+         link.type = 'text/css';
+         link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
+         document.getElementsByTagName( 'head' )[0].appendChild( link );
+     &lt;/script&gt;
  
- 		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;
+     &lt;!--[if lt IE 9]&gt;
+     &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
+     &lt;![endif]--&gt;
+ &lt;/head&gt;
  
- 		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
- 		&lt;meta name="author" content="Hakim El Hattab"&gt;
- 
- 		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
- 		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
- 
- 		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
- 
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
- 
- 		&lt;!-- Theme used for syntax highlighting of code --&gt;
- 		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
- 
- 		&lt;!-- Printing and PDF exports --&gt;
- 		&lt;script&gt;
- 			var link = document.createElement( 'link' );
- 			link.rel = 'stylesheet';
- 			link.type = 'text/css';
- 			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
- 			document.getElementsByTagName( 'head' )[0].appendChild( link );
- 		&lt;/script&gt;
- 
- 		&lt;!--[if lt IE 9]&gt;
- 		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
- 		&lt;![endif]--&gt;
- 	&lt;/head&gt;
</t>
<t tx="leo.20170115114300.30">(uncached) leo.20161014111031.10
Diff...
-                                &lt;section&gt;
- 					&lt;h2&gt;第一次用這個軟體畫圖,有點不太習慣,但有些功能還是蠻方便的,最後靠著團隊的力量還是畫出作品了,錄好影片後因為同學的VIMEO忘記登出所以有些組員就直接上傳了影片,最後就跟他借VIMEO用了,上課時也有開始恢復GITHUB的記憶了開心&lt;/h2&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
-                               
- 				&lt;!-- Example of nested vertical slides --&gt;
- 				&lt;section&gt;
? ----
+ &lt;/section&gt;
?  +
- 					&lt;section&gt;
- 						&lt;p&gt;作業2&lt;/p&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.300">(uncached) leo.20170112140710.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.301">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.302">@others
</t>
<t tx="leo.20170115114300.303">(uncached) leo.20170112140710.3
Diff...
+ ## 2017-01-06 第十七週
+ 
</t>
<t tx="leo.20170115114300.304">## 2017-01-06 第十七週

</t>
<t tx="leo.20170115114300.305"></t>
<t tx="leo.20170115114300.306">(uncached) leo.20170112140710.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.307">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.308">@others
</t>
<t tx="leo.20170115114300.309">(uncached) leo.20170112140710.5
Diff...
+ ## 利用約束條件,使機構作相對運動
+ 
+ &lt;iframe src="https://player.vimeo.com/video/199112247" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.31">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.310">## 利用約束條件,使機構作相對運動

&lt;iframe src="https://player.vimeo.com/video/199112247" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.311"></t>
<t tx="leo.20170115114300.312">(uncached) leo.20170113103445.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.313">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.314">@others
</t>
<t tx="leo.20170115114300.315">(uncached) leo.20170113103445.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.316">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.317">@others
</t>
<t tx="leo.20170115114300.318">(uncached) leo.20170113103445.3
Diff...
+ ## 2017-01-13 第十八週
+ 
</t>
<t tx="leo.20170115114300.319">## 2017-01-13 第十八週

</t>
<t tx="leo.20170115114300.32">                               &lt;section&gt;
					&lt;h2&gt;第一次用這個軟體畫圖,有點不太習慣,但有些功能還是蠻方便的,最後靠著團隊的力量還是畫出作品了,錄好影片後因為同學的VIMEO忘記登出所以有些組員就直接上傳了影片,最後就跟他借VIMEO用了,上課時也有開始恢復GITHUB的記憶了開心&lt;/h2&gt;
@others
                              
				&lt;!-- Example of nested vertical slides --&gt;
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業2&lt;/p&gt;
</t>
<t tx="leo.20170115114300.320"></t>
<t tx="leo.20170115114300.321">(uncached) leo.20170113103445.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.322">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.323">@others
</t>
<t tx="leo.20170115114300.324">(uncached) leo.20170113103445.5
Diff...
+ ## 2016 Fall 電腦輔助設計與實習期末自評總結</t>
<t tx="leo.20170115114300.325">## 2016 Fall 電腦輔助設計與實習期末自評總結</t>
<t tx="leo.20170115114300.326"></t>
<t tx="leo.20170115114300.33">(uncached) leo.20161014111031.11
Diff...
- 				
-                               &lt;/section&gt;
+ 中秋連假
+ 
</t>
<t tx="leo.20170115114300.34">中秋連假

</t>
<t tx="leo.20170115114300.35">				
                              &lt;/section&gt;
</t>
<t tx="leo.20170115114300.36">(uncached) leo.20161014111031.24
Diff...
- 				
+ &lt;section&gt;
  @others
- 				&lt;/section&gt;
? ----          -
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.37">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.38">				
@others
				&lt;/section&gt;
</t>
<t tx="leo.20170115114300.39">(uncached) leo.20161104010248.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
  						
- 					
- @others
- 					&lt;section&gt;
- 				
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
</t>
<t tx="leo.20170115114300.4">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
&lt;title&gt;
2016 Fall 電腦輔助設計實習課程
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="leo.20170115114300.40">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.41">						
					
@others
					&lt;section&gt;
				
					&lt;/section&gt;
					&lt;section&gt;
						&lt;h2&gt;Basement Level 2&lt;/h2&gt;
</t>
<t tx="leo.20170115114300.42">(uncached) leo.20161104010248.2
Diff...
- 					&lt;/section&gt;
- 					
+ ## 2016-09-23 第二週
+ 
</t>
<t tx="leo.20170115114300.43">## 2016-09-23 第二週

</t>
<t tx="leo.20170115114300.44">					&lt;/section&gt;
					
</t>
<t tx="leo.20170115114300.45">(uncached) leo.20161014111031.25
Diff...
- 						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
- 						&lt;br&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 				&lt;section&gt;
? ----
+ &lt;/section&gt;
?  +
+ 
+ 
- 			
- 			&lt;h2&gt;心得&lt;/h2&gt;
- 				&lt;p&gt;用了solvespace跟onshape後我比較習慣oonshape因為他跟我之前學過的軟體很類似所以用起來有熟悉的感覺,而solvespace我比較不太會用,因為它的功能用法太多的限制,如果少了點你的功能就會不能用,還有一點再標註時太過於複雜,但是還是很感謝老師介紹這兩個軟體給我們,我也從中學習很多謝謝.&lt;/p&gt;
  						
</t>
<t tx="leo.20170115114300.46">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.47">						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
@others
				&lt;section&gt;
			
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;用了solvespace跟onshape後我比較習慣oonshape因為他跟我之前學過的軟體很類似所以用起來有熟悉的感覺,而solvespace我比較不太會用,因為它的功能用法太多的限制,如果少了點你的功能就會不能用,還有一點再標註時太過於複雜,但是還是很感謝老師介紹這兩個軟體給我們,我也從中學習很多謝謝.&lt;/p&gt;
						
</t>
<t tx="leo.20170115114300.48">(uncached) leo.20161014111031.26
Diff...
+ ## 建立
+ ## 40423226.github.io名稱的倉儲
- 						&lt;a href="#/2"&gt;
- 							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
- 						&lt;/a&gt;
- 					&lt;/section&gt;
- 				&lt;/section&gt;
  
+ &lt;iframe src="https://player.vimeo.com/video/190063679" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170115114300.49">## 建立
## 40423226.github.io名稱的倉儲

&lt;iframe src="https://player.vimeo.com/video/190063679" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170115114300.5">
	&lt;head&gt;
		&lt;meta charset="utf-8"&gt;

		&lt;title&gt;reveal.js – The HTML Presentation Framework&lt;/title&gt;

		&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
		&lt;meta name="author" content="Hakim El Hattab"&gt;

		&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
		&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;

		&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;

		&lt;!-- Theme used for syntax highlighting of code --&gt;
		&lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

		&lt;!-- Printing and PDF exports --&gt;
		&lt;script&gt;
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		&lt;/script&gt;

		&lt;!--[if lt IE 9]&gt;
		&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
		&lt;![endif]--&gt;
	&lt;/head&gt;
</t>
<t tx="leo.20170115114300.50">						&lt;a href="#/2"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170115114300.51">(uncached) leo.20161014111031.27
Diff...
- 					
- 					&lt;/section&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
- 						&lt;p&gt;第二週 1.radinsed半徑 2.diameter直徑 3.place放置 4.symmetrically對稱 5.lnitially開始 6.oriented定位 7.axes軸 8.indicated表示 9.respectively分別 10.parallel平行 11.extruding長出 12.automatically自動 13.coincident一模一樣 14.constraint約束 15.horizontal橫 16.perpendicular垂直 17.step圖(格式)
-                                                 &lt;p&gt;錄影工具:sharex 1.paths 2.task → screen recorder → options 開始錄製:shift+ print screen 射出成型軟體:moldex3d
-                                                 &lt;p&gt;作業 成品影片:https://vimeo.com/185115914
- 					&lt;/p&gt;
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
- 					
+ 						
? +
</t>
<t tx="leo.20170115114300.52">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.53">					
					&lt;/section&gt;
@others
						&lt;p&gt;第二週 1.radinsed半徑 2.diameter直徑 3.place放置 4.symmetrically對稱 5.lnitially開始 6.oriented定位 7.axes軸 8.indicated表示 9.respectively分別 10.parallel平行 11.extruding長出 12.automatically自動 13.coincident一模一樣 14.constraint約束 15.horizontal橫 16.perpendicular垂直 17.step圖(格式)
                                                &lt;p&gt;錄影工具:sharex 1.paths 2.task → screen recorder → options 開始錄製:shift+ print screen 射出成型軟體:moldex3d
                                                &lt;p&gt;作業 成品影片:https://vimeo.com/185115914
					&lt;/p&gt;
					
</t>
<t tx="leo.20170115114300.54">(uncached) leo.20161014111031.28
Diff...
+ ## 把分支的預設值改為gh-pages
  
+ &lt;iframe src="https://player.vimeo.com/video/190064489" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;- 				&lt;section&gt;
- 					&lt;h2&gt;筆記&lt;/h2&gt;
</t>
<t tx="leo.20170115114300.55">## 把分支的預設值改為gh-pages

&lt;iframe src="https://player.vimeo.com/video/190064489" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.56">
				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
</t>
<t tx="leo.20170115114300.57">(uncached) leo.20161014111031.37
Diff...
- 
+ &lt;section&gt;
  @others
- 				&lt;/section&gt;
? ----          -
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.58">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.59">
@others
				&lt;/section&gt;
</t>
<t tx="leo.20170115114300.6">(uncached) leo.20161014111031.4
Diff...
+ &lt;body&gt;
+ @others
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
+ &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
+ &lt;script&gt;
+         // More info https://github.com/hakimel/reveal.js#configuration
+         Reveal.initialize({
+             controls: true,
+             progress: true,
+             history: true,
+             center: true,
  
- @others
+             transition: 'slide', // none/fade/slide/convex/concave/zoom
+ 
+             // More info https://github.com/hakimel/reveal.js#dependencies
+             dependencies: [
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
+                 { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
+             ]
+         });
+ &lt;/script&gt;
+ &lt;/body&gt;
</t>
<t tx="leo.20170115114300.60">(uncached) leo.20161104010457.1
Diff...
- 				&lt;section&gt;
- 					&lt;h2&gt;筆記&lt;/h2&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
-   &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
- 				
- 				&lt;/section&gt;
? ----
+ &lt;/section&gt;
  
- 					&lt;section&gt;
+ 
+ 						
</t>
<t tx="leo.20170115114300.61">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.62">				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
@others
  &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
				
				&lt;/section&gt;

					&lt;section&gt;
</t>
<t tx="leo.20170115114300.63">(uncached) leo.20161104010457.2
Diff...
- 			
-   &lt;p&gt;第三週 proxy設定:proxy.mde.tw 通訊阜:3128 去聲音指令:ffmpeg.exe -i 檔名 -c copy -an out.mp4 字幕指令:ffmpeg.exe -i out.mp4 -vf subtitles=in.srt out2.mp4 安裝pelican指令:pip install pelican
+ ## 2016-09-30 第三週
+ 
</t>
<t tx="leo.20170115114300.64">## 2016-09-30 第三週

</t>
<t tx="leo.20170115114300.65">			
  &lt;p&gt;第三週 proxy設定:proxy.mde.tw 通訊阜:3128 去聲音指令:ffmpeg.exe -i 檔名 -c copy -an out.mp4 字幕指令:ffmpeg.exe -i out.mp4 -vf subtitles=in.srt out2.mp4 安裝pelican指令:pip install pelican
</t>
<t tx="leo.20170115114300.66">(uncached) leo.20161014111031.38
Diff...
- 						&lt;p&gt;作業3&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/DeiSRrQImVA" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 					&lt;section&gt;
? -----
+ &lt;/section&gt;
?  +
+ 
+ 
- 						&lt;p&gt;作業3&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/-8yrDF_-v2w" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				
  						
</t>
<t tx="leo.20170115114300.67">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.68">						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/DeiSRrQImVA" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
@others
					&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/-8yrDF_-v2w" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
						
</t>
<t tx="leo.20170115114300.69">(uncached) leo.20161014111031.39
Diff...
+ ## 複製網誌和簡報的設定檔
+ ## 到2016fallcadp_hw的倉儲
- 				
- 						
- 					
- 					&lt;/section&gt;
  
- 				&lt;section&gt;
+ &lt;iframe src="https://player.vimeo.com/video/190065696" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
</t>
<t tx="leo.20170115114300.7">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,

            transition: 'slide', // none/fade/slide/convex/concave/zoom

            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="leo.20170115114300.70">## 複製網誌和簡報的設定檔
## 到2016fallcadp_hw的倉儲

&lt;iframe src="https://player.vimeo.com/video/190065696" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170115114300.71">				
						
					
					&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170115114300.72">(uncached) leo.20161104010537.1
Diff...
- 					
- 					&lt;/section&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
- 						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
- 						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
- 						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
- 						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
- 					&lt;/section&gt;
? -----
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20170115114300.73">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.74">					
					&lt;/section&gt;
@others
						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
					&lt;/section&gt;
</t>
<t tx="leo.20170115114300.75">(uncached) leo.20161104010537.2
Diff...
+ ## 更改2016fallcadp_hw的
+ ## README.md檔案
  
+ &lt;iframe src="https://player.vimeo.com/video/190066620" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ 
+ 
- 					&lt;section&gt;
- 						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
- 						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
- 						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
- 						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
</t>
<t tx="leo.20170115114300.76">## 更改2016fallcadp_hw的
## README.md檔案

&lt;iframe src="https://player.vimeo.com/video/190066620" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;


</t>
<t tx="leo.20170115114300.77">
					&lt;section&gt;
						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
</t>
<t tx="leo.20170115114300.78">(uncached) leo.20161014111031.40
Diff...
- 
+ &lt;section&gt;
  @others
- 				
+ &lt;/section&gt;</t>
<t tx="leo.20170115114300.79">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20170115114300.8">
@others
</t>
<t tx="leo.20170115114300.80">
@others
				
</t>
<t tx="leo.20170115114300.81">(uncached) leo.20161104010854.1
Diff...
- 				&lt;section&gt;
- 						&lt;p&gt;作業3&lt;/p&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
  						
- 					
- 					&lt;/section&gt;
- 
- 				&lt;section&gt;
</t>
<t tx="leo.20170115114300.82">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20170115114300.83">				&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
@others
						
					
					&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170115114300.84">(uncached) leo.20161104010854.2
Diff...
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_Zcs7yA9ZKw" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				
+ ## 2016-10-07 第四週
+ 
</t>
<t tx="leo.20170115114300.85">## 2016-10-07 第四週

</t>
<t tx="leo.20170115114300.86">					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_Zcs7yA9ZKw" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
</t>
<t tx="leo.20170115114300.87">(uncached) leo.20161014111031.41
Diff...
- 						&lt;p&gt;作業3&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ydZxFfLEyMU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
- 				&lt;section&gt;
? ----
+ &lt;/section&gt;
?  +
+ 
+ 
+ 
- 					&lt;section&gt;
- 						&lt;p&gt;作業3請往下 作業4請往右&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Ft__ZZO_niQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				
  						
</t>
<t tx="leo.20170115114300.88">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20170115114300.89">						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ydZxFfLEyMU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
@others
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業3請往下 作業4請往右&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Ft__ZZO_niQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
						
</t>
<t tx="leo.20170115114300.9">(uncached) leo.20161014111031.5
Diff...
- 	&lt;body&gt;
+ &lt;div class="reveal"&gt;
  @others
+ &lt;/div&gt;
+ 
</t>
<t tx="leo.20170115114300.90">(uncached) leo.20161014111031.42
Diff...
+ ## 設定使用者資料
+ ## 讓可攜程式更方便
- 						
- 					
- 					&lt;/section&gt;
  
+ &lt;iframe src="https://player.vimeo.com/video/190072906" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.91">## 設定使用者資料
## 讓可攜程式更方便

&lt;iframe src="https://player.vimeo.com/video/190072906" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.92">						
					
					&lt;/section&gt;

</t>
<t tx="leo.20170115114300.93">(uncached) leo.20161014111031.43
Diff...
- 					
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
+ @others
+     &lt;/script&gt;
- 					&lt;/section&gt;
? -----
+ &lt;/section&gt;
  
- @others
+ 
+ 
  						
- 					
- 					&lt;/section&gt;
- 					&lt;section&gt;
- 						&lt;p&gt;作業3&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/BjNY2ZK_0OQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.94">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20170115114300.95">					
					&lt;/section&gt;

@others
						
					
					&lt;/section&gt;
					&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/BjNY2ZK_0OQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170115114300.96">(uncached) leo.20161014111031.44
Diff...
- 					&lt;section&gt;
- 						&lt;p&gt;作業3&lt;/p&gt;
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gPo1dmp7f5c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
- 				
+ ## 用2016fallcadp_bg6的名稱
+ ## 建立小組倉儲
+ 
+ &lt;iframe src="https://player.vimeo.com/video/190075715" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.97">## 用2016fallcadp_bg6的名稱
## 建立小組倉儲

&lt;iframe src="https://player.vimeo.com/video/190075715" width="640" height="347" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;</t>
<t tx="leo.20170115114300.98">					&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gPo1dmp7f5c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
</t>
<t tx="leo.20170115114300.99">(uncached) leo.20161103232830.1
Diff...
- 						
+ &lt;section&gt;
  @others
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_IBrCR0BCEs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;/section&gt;</t>
<t tx="leo.20170116002413.10"> &lt;/p&gt;
				&lt;/section&gt;
@others
					&lt;h4&gt;作業1&lt;/h4&gt;
					&lt;iframe src="https://player.vimeo.com/video/185824836" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
			
                              &lt;/section&gt;
				
</t>
<t tx="leo.20170116002413.100">				&lt;/section&gt;

				&lt;section&gt;
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;在改尺寸時遇到了一點麻煩,我們在討論是每一個草圖都要改,還是只要去改最外面的輪廓就好,這次作業很有挑戰&lt;p&gt;
</t>
<t tx="leo.20170116002413.101"></t>
<t tx="leo.20170116002413.102">(uncached) leo.20161104203720.1
Diff...
+                                  &lt;section&gt;
  @others
+ 			&lt;/div&gt;
</t>
<t tx="leo.20170116002413.103">                                 &lt;section&gt;
@others
			&lt;/div&gt;
</t>
<t tx="leo.20170116002413.104">@others
</t>
<t tx="leo.20170116002413.105">(uncached) leo.20161104203720.2
Diff...
+ 					&lt;p&gt;作業6&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pCNcDhYsaM8" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
  @others
+ 				&lt;section&gt;
+ 					&lt;p&gt;作業6&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pIv-YnnAzPE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				&lt;/section&gt;
+ 
</t>
<t tx="leo.20170116002413.106">					&lt;p&gt;作業6&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pCNcDhYsaM8" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
@others
				&lt;section&gt;
					&lt;p&gt;作業6&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/pIv-YnnAzPE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170116002413.107">@others
</t>
<t tx="leo.20170116002413.108">(uncached) leo.20161104203720.3
Diff...
+ 				&lt;/section&gt;
+ 
</t>
<t tx="leo.20170116002413.109">				&lt;/section&gt;

</t>
<t tx="leo.20170116002413.11"> &lt;/p&gt;
				&lt;/section&gt;
@others
					&lt;h4&gt;作業1&lt;/h4&gt;
					&lt;iframe src="https://player.vimeo.com/video/185818182" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
			
                              &lt;/section&gt;
				
</t>
<t tx="leo.20170116002413.110"></t>
<t tx="leo.20170116002413.111">(uncached) leo.20161104203720.4
Diff...
+ 				&lt;section&gt;
+ 					&lt;p&gt;作業6&lt;/p&gt;
  @others
+ 					&lt;h2&gt;心得&lt;/h2&gt;
+ 					&lt;p&gt;這一次大家的討論還是非常的熱絡,大家都會去從問題中學到新的知識,也會學習到解決問題的方法,而不是碰到問題就停滯不前了&lt;p&gt;
+ 				&lt;/section&gt;
+ 
+ 				
</t>
<t tx="leo.20170116002413.112">				&lt;section&gt;
					&lt;p&gt;作業6&lt;/p&gt;
@others
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;這一次大家的討論還是非常的熱絡,大家都會去從問題中學到新的知識,也會學習到解決問題的方法,而不是碰到問題就停滯不前了&lt;p&gt;
				&lt;/section&gt;

				
</t>
<t tx="leo.20170116002413.113">@others
</t>
<t tx="leo.20170116002413.114">(uncached) leo.20161104203720.5
Diff...
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/8rT5k7EoovE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				&lt;/section&gt;
+ 
+ 				&lt;section&gt;
</t>
<t tx="leo.20170116002413.115">					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/8rT5k7EoovE" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170116002413.116"></t>
<t tx="leo.20170116002413.117">(uncached) leo.20161115000909.2
Diff...
  		&lt;/div&gt;
  
  @others
  
  		&lt;script&gt;
+ 
  			// More info https://github.com/hakimel/reveal.js#configuration
  			Reveal.initialize({
</t>
<t tx="leo.20170116002413.118">		&lt;/div&gt;

@others

		&lt;script&gt;

			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
</t>
<t tx="leo.20170116002413.119">		&lt;/div&gt;

@others

		&lt;script&gt;
			// More info https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
</t>
<t tx="leo.20170116002413.12">(uncached) leo.20161014111031.10
Diff...
                                 &lt;section&gt;
- 					&lt;h2&gt;這一次的作業我拍好影片,但是我借用德威的VIMEO上傳的時候德威忘記登出所以就直接借用他的了,我們這組是一起討論後最後才成功畫出作品的,很喜歡團隊合作的感覺,蠻有成就感的雖然在畫的時候失敗了一次又一次哈哈&lt;/h2&gt;
+ 					&lt;h2&gt;第一次用這個軟體畫圖,有點不太習慣,但有些功能還是蠻方便的,最後靠著團隊的力量還是畫出作品了,錄好影片後因為同學的VIMEO忘記登出所以有些組員就直接上傳了影片,最後就跟他借VIMEO用了,上課時也有開始恢復GITHUB的記憶了開心&lt;/h2&gt;
  @others
                                
  				&lt;!-- Example of nested vertical slides --&gt;
  				&lt;section&gt;
  					&lt;section&gt;
  						&lt;p&gt;作業2&lt;/p&gt;
</t>
<t tx="leo.20170116002413.120">(uncached) leo.20161115000909.4
Diff...
  				controls: true,
  				progress: true,
  @others
+ 
  				// More info https://github.com/hakimel/reveal.js#dependencies
  				dependencies: [
  					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
  					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20170116002413.121">				controls: true,
				progress: true,
@others

				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20170116002413.122">				controls: true,
				progress: true,
@others
				// More info https://github.com/hakimel/reveal.js#dependencies
				dependencies: [
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
</t>
<t tx="leo.20170116002413.123">(uncached) leo.20161115000909.5
Diff...
  				history: true,
  				center: true,
+ 
  				transition: 'slide', // none/fade/slide/convex/concave/zoom
</t>
<t tx="leo.20170116002413.124">				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom
</t>
<t tx="leo.20170116002413.125">				history: true,
				center: true,
				transition: 'slide', // none/fade/slide/convex/concave/zoom
</t>
<t tx="leo.20170116002413.126">(uncached) leo.20161124210839.2
Diff...
  					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
  					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
  @others
+ 
  		&lt;/script&gt;
  
  	&lt;/body&gt;
</t>
<t tx="leo.20170116002413.127">					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
@others

		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20170116002413.128">					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
					{ src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true }
@others
		&lt;/script&gt;

	&lt;/body&gt;
</t>
<t tx="leo.20170116002413.13">                               &lt;section&gt;
					&lt;h2&gt;第一次用這個軟體畫圖,有點不太習慣,但有些功能還是蠻方便的,最後靠著團隊的力量還是畫出作品了,錄好影片後因為同學的VIMEO忘記登出所以有些組員就直接上傳了影片,最後就跟他借VIMEO用了,上課時也有開始恢復GITHUB的記憶了開心&lt;/h2&gt;
@others
                              
				&lt;!-- Example of nested vertical slides --&gt;
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業2&lt;/p&gt;
</t>
<t tx="leo.20170116002413.14">                               &lt;section&gt;
					&lt;h2&gt;這一次的作業我拍好影片,但是我借用德威的VIMEO上傳的時候德威忘記登出所以就直接借用他的了,我們這組是一起討論後最後才成功畫出作品的,很喜歡團隊合作的感覺,蠻有成就感的雖然在畫的時候失敗了一次又一次哈哈&lt;/h2&gt;
@others
                              
				&lt;!-- Example of nested vertical slides --&gt;
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業2&lt;/p&gt;
</t>
<t tx="leo.20170116002413.15">(uncached) leo.20161014111031.25
Diff...
  						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
  						&lt;br&gt;
  @others
  				&lt;section&gt;
  			
  			&lt;h2&gt;心得&lt;/h2&gt;
- 				&lt;p&gt;在試用了老師所介紹的兩套軟體-SolveSpace 和 Onshape後 覺得Onshape較SolveSpace好用，而Onshape和我們常用的soildwork還滿像的 所以用起來比較習慣。SolveSpace沒一些快速指令，每執行完一項功能，就要重新點選，覺得比較麻煩一點!!&lt;/p&gt;
+ 				&lt;p&gt;用了solvespace跟onshape後我比較習慣oonshape因為他跟我之前學過的軟體很類似所以用起來有熟悉的感覺,而solvespace我比較不太會用,因為它的功能用法太多的限制,如果少了點你的功能就會不能用,還有一點再標註時太過於複雜,但是還是很感謝老師介紹這兩個軟體給我們,我也從中學習很多謝謝.&lt;/p&gt;
  						
</t>
<t tx="leo.20170116002413.16">						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
@others
				&lt;section&gt;
			
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;用了solvespace跟onshape後我比較習慣oonshape因為他跟我之前學過的軟體很類似所以用起來有熟悉的感覺,而solvespace我比較不太會用,因為它的功能用法太多的限制,如果少了點你的功能就會不能用,還有一點再標註時太過於複雜,但是還是很感謝老師介紹這兩個軟體給我們,我也從中學習很多謝謝.&lt;/p&gt;
						
</t>
<t tx="leo.20170116002413.17">						&lt;p&gt;That's it, time to go back up.&lt;/p&gt;
						&lt;br&gt;
@others
				&lt;section&gt;
			
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;在試用了老師所介紹的兩套軟體-SolveSpace 和 Onshape後 覺得Onshape較SolveSpace好用，而Onshape和我們常用的soildwork還滿像的 所以用起來比較習慣。SolveSpace沒一些快速指令，每執行完一項功能，就要重新點選，覺得比較麻煩一點!!&lt;/p&gt;
						
</t>
<t tx="leo.20170116002413.18">(uncached) leo.20161014111031.37
Diff...
  
  @others
+ 				&lt;/section&gt;
</t>
<t tx="leo.20170116002413.19">
@others
				&lt;/section&gt;
</t>
<t tx="leo.20170116002413.2"></t>
<t tx="leo.20170116002413.20">
@others
</t>
<t tx="leo.20170116002413.21">(uncached) leo.20161104010457.1
Diff...
  				&lt;section&gt;
  					&lt;h2&gt;筆記&lt;/h2&gt;
  @others
    &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
  				
  				&lt;/section&gt;
  
+ 					&lt;section&gt;
</t>
<t tx="leo.20170116002413.22">				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
@others
  &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
				
				&lt;/section&gt;

					&lt;section&gt;
</t>
<t tx="leo.20170116002413.23">				&lt;section&gt;
					&lt;h2&gt;筆記&lt;/h2&gt;
@others
  &lt;p&gt;第四週 刪除指令:git rm -rf 下載分支內的東西:git submodule update --init --recursive 子模組的對應版本更新到目前最新提交:git submodule foreach "(git checkout gh-pages; git pull)"
				
				&lt;/section&gt;

</t>
<t tx="leo.20170116002413.24">(uncached) leo.20161014111031.38
Diff...
+ 						&lt;p&gt;作業3&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/DeiSRrQImVA" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
  @others
+ 					&lt;section&gt;
- 					&lt;p&gt;作業3&lt;/p&gt;
+ 						&lt;p&gt;作業3&lt;/p&gt;
? +
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/JFKJpplaqDs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                                    ^ ^^^^^^^^^
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/-8yrDF_-v2w" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                                    ^^^^^ ^^^^^
+ 				
+ 						
</t>
<t tx="leo.20170116002413.25">						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/DeiSRrQImVA" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
@others
					&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/-8yrDF_-v2w" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
						
</t>
<t tx="leo.20170116002413.26">@others
					&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/JFKJpplaqDs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.27">(uncached) leo.20161014111031.39
Diff...
  				
+ 						
- 				
+ 					
? +
+ 					&lt;/section&gt;
+ 
  				&lt;section&gt;
</t>
<t tx="leo.20170116002413.28">				
						
					
					&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170116002413.29">				
				
				&lt;section&gt;
</t>
<t tx="leo.20170116002413.3">(uncached) leo.20161014111031.8
Diff...
  			&lt;div class="slides"&gt;
  				&lt;section&gt;
- 					&lt;h1&gt;40423201 黃上芸 計算機程式課程&lt;/h1&gt;
? 					           ^ ^^^
+ 					&lt;h1&gt;40423203 鄭惟芯 計算機程式課程&lt;/h1&gt;
? 					           ^ ^^^
  					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
  					&lt;p&gt;
  						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
  					&lt;/p&gt;
                      &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
  				&lt;/section&gt;
</t>
<t tx="leo.20170116002413.30">(uncached) leo.20161104010537.1
Diff...
+ 					
+ 					&lt;/section&gt;
  @others
+ 						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
+ 						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
+ 						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
+ 						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
+ 					&lt;/section&gt;
</t>
<t tx="leo.20170116002413.31">					
					&lt;/section&gt;
@others
						&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						&lt;p class="fragment fade-up"&gt;fade-up (also down, left and right!)&lt;/p&gt;
						&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						&lt;p&gt;Highlight &lt;span class="fragment highlight-red"&gt;red&lt;/span&gt; &lt;span class="fragment highlight-blue"&gt;blue&lt;/span&gt; &lt;span class="fragment highlight-green"&gt;green&lt;/span&gt;&lt;/p&gt;
					&lt;/section&gt;
</t>
<t tx="leo.20170116002413.32">@others
</t>
<t tx="leo.20170116002413.33">(uncached) leo.20161104010537.2
Diff...
+ 
+ 					&lt;section&gt;
+ 						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
+ 						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
+ 						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
+ 						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
</t>
<t tx="leo.20170116002413.34">
					&lt;section&gt;
						&lt;h2&gt;Fragment Styles&lt;/h2&gt;
						&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
</t>
<t tx="leo.20170116002413.35"></t>
<t tx="leo.20170116002413.36">(uncached) leo.20161014111031.40
Diff...
+ 
  @others
+ 				
</t>
<t tx="leo.20170116002413.37">
@others
				
</t>
<t tx="leo.20170116002413.38">@others
</t>
<t tx="leo.20170116002413.39">(uncached) leo.20161104010854.1
Diff...
+ 				&lt;section&gt;
+ 						&lt;p&gt;作業3&lt;/p&gt;
  @others
+ 						
+ 					
+ 					&lt;/section&gt;
+ 
+ 				&lt;section&gt;
</t>
<t tx="leo.20170116002413.4">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40423203 鄭惟芯 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;
</t>
<t tx="leo.20170116002413.40">				&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
@others
						
					
					&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170116002413.41">@others
</t>
<t tx="leo.20170116002413.42">(uncached) leo.20161104010854.2
Diff...
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_Zcs7yA9ZKw" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				
</t>
<t tx="leo.20170116002413.43">					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_Zcs7yA9ZKw" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
</t>
<t tx="leo.20170116002413.44"></t>
<t tx="leo.20170116002413.45">(uncached) leo.20161014111031.41
Diff...
+ 						&lt;p&gt;作業3&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ydZxFfLEyMU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				
  @others
+ 				&lt;section&gt;
+ 					&lt;section&gt;
+ 						&lt;p&gt;作業3請往下 作業4請往右&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Ft__ZZO_niQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				
+ 						
</t>
<t tx="leo.20170116002413.46">						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ydZxFfLEyMU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
@others
				&lt;section&gt;
					&lt;section&gt;
						&lt;p&gt;作業3請往下 作業4請往右&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Ft__ZZO_niQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
						
</t>
<t tx="leo.20170116002413.47">@others
</t>
<t tx="leo.20170116002413.48">(uncached) leo.20161014111031.42
Diff...
+ 						
+ 					
+ 					&lt;/section&gt;
+ 
</t>
<t tx="leo.20170116002413.49">						
					
					&lt;/section&gt;

</t>
<t tx="leo.20170116002413.5">			&lt;div class="slides"&gt;
				&lt;section&gt;
					&lt;h1&gt;40423201 黃上芸 計算機程式課程&lt;/h1&gt;
					&lt;h3&gt;The HTML Presentation Framework&lt;/h3&gt;
					&lt;p&gt;
						&lt;small&gt;Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;&lt;/small&gt;
					&lt;/p&gt;
                    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
				&lt;/section&gt;
</t>
<t tx="leo.20170116002413.50"></t>
<t tx="leo.20170116002413.51">(uncached) leo.20161014111031.43
Diff...
+ 					
+ 					&lt;/section&gt;
+ 
  @others
+ 						
+ 					
+ 					&lt;/section&gt;
+ 					&lt;section&gt;
+ 						&lt;p&gt;作業3&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/BjNY2ZK_0OQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.52">					
					&lt;/section&gt;

@others
						
					
					&lt;/section&gt;
					&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/BjNY2ZK_0OQ" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.53">@others
</t>
<t tx="leo.20170116002413.54">(uncached) leo.20161014111031.44
Diff...
+ 					&lt;section&gt;
+ 						&lt;p&gt;作業3&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gPo1dmp7f5c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				
</t>
<t tx="leo.20170116002413.55">					&lt;section&gt;
						&lt;p&gt;作業3&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gPo1dmp7f5c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				
</t>
<t tx="leo.20170116002413.56"></t>
<t tx="leo.20170116002413.57">(uncached) leo.20161103232830.1
Diff...
+ 						
  @others
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_IBrCR0BCEs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.58">						
@others
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/_IBrCR0BCEs" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.59">@others
</t>
<t tx="leo.20170116002413.6">(uncached) leo.20161014111031.9
Diff...
  					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
  @others
- 					&lt;iframe src="https://player.vimeo.com/video/190123005" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                 ^^^^                       ^^
+ 					&lt;iframe src="https://player.vimeo.com/video/190128689" width="640" height="325" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                 ^^^^                       ^^
</t>
<t tx="leo.20170116002413.60">(uncached) leo.20161104011343.1
Diff...
+ 					也
+ 					&lt;/section&gt;
  @others
+ 			&lt;h2&gt;心得&lt;/h2&gt;
+ 				&lt;p&gt;心得:老師這次的作業我們組員都付出了時間和汗水一起完成,我也從其中利用程式增進我不少的繪圖技巧與知識&lt;p&gt;
+ 		
+ 					
+ 					&lt;/section&gt;
</t>
<t tx="leo.20170116002413.61">					也
					&lt;/section&gt;
@others
			&lt;h2&gt;心得&lt;/h2&gt;
				&lt;p&gt;心得:老師這次的作業我們組員都付出了時間和汗水一起完成,我也從其中利用程式增進我不少的繪圖技巧與知識&lt;p&gt;
		
					
					&lt;/section&gt;
</t>
<t tx="leo.20170116002413.62">@others
</t>
<t tx="leo.20170116002413.63">(uncached) leo.20161104011343.2
Diff...
+ 					&lt;section&gt;
+ 			
</t>
<t tx="leo.20170116002413.64">					&lt;section&gt;
			
</t>
<t tx="leo.20170116002413.65"></t>
<t tx="leo.20170116002413.66">(uncached) leo.20161103232830.2
Diff...
+ 					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
+ 						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
  @others
- 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/QPBiOIqfW28" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                                    ^^ ^^^^^^^^
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/AdBvhRRuhgU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                                    ^^ ^^^^^^^^
+ 				&lt;/section&gt;
+ 
+ 				&lt;section&gt;
+ 					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20170116002413.67">					&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
						&lt;h2&gt;... and GIFs!&lt;/h2&gt;
@others
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/AdBvhRRuhgU" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20170116002413.68">@others
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/QPBiOIqfW28" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.69">(uncached) leo.20161103232830.3
Diff...
+ 					&lt;/section&gt;
  				&lt;/section&gt;
  
  				&lt;section&gt;
  					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20170116002413.7">					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
@others
					&lt;iframe src="https://player.vimeo.com/video/190128689" width="640" height="325" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.70">					&lt;/section&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20170116002413.71">				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
</t>
<t tx="leo.20170116002413.72">(uncached) leo.20161103232832.1
Diff...
+ 				&lt;/section&gt;
  @others
- 				&lt;/div&gt;
+ 				&lt;section&gt;
</t>
<t tx="leo.20170116002413.73">				&lt;/section&gt;
@others
				&lt;section&gt;
</t>
<t tx="leo.20170116002413.74">@others
				&lt;/div&gt;
</t>
<t tx="leo.20170116002413.75">(uncached) leo.20161104011407.1
Diff...
+ 
+ 				&lt;section&gt;
  @others
+ 				&lt;/section&gt;
+ 
+ 				&lt;section&gt;
+ 					&lt;p&gt;作業4&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/UEyyR0mh9Kk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.76">
				&lt;section&gt;
@others
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/UEyyR0mh9Kk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.77">@others
</t>
<t tx="leo.20170116002413.78">(uncached) leo.20161104011407.2
Diff...
+ 			                &lt;p&gt;作業4&lt;/p&gt;
+ 			                &lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gun-R6LVY3c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.79">			                &lt;p&gt;作業4&lt;/p&gt;
			                &lt;iframe width="560" height="315" src="https://www.youtube.com/embed/gun-R6LVY3c" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.8">					4.創 2016fallcadp_bg100(組別) 將2016fallcadp_bg100 clone下來 2016fallcadp_bg100 git branch git checkout gh-pages git branch(再次檢查) 將自己的2016fallcadp_hw clone網址複製 git submodule add -b gh-pages 網址 學號 git staus(檢查) 依序將隊友的資料夾加入 git add -A git commit -m "名稱" git push origin gh-pages
@others
					&lt;iframe src="https://player.vimeo.com/video/190123005" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.80"></t>
<t tx="leo.20170116002413.81">(uncached) leo.20161103232832.2
Diff...
+ 				&lt;/section&gt;
+ 
  @others
  				&lt;section&gt;
  					&lt;h2&gt;心得&lt;/h2&gt;
- 					&lt;p&gt;這一次我們這組整個討論下來,覺得這一次的作業比較複雜一點但,在這一次又有學到新的知識,又得到了一些還沒學過的能力&lt;p&gt;
+ 					&lt;p&gt;老師給我們的零件網站,透過這一次的作業,我發現非常實用,以後應該還會多多利用那個網站,是個非常方便的網站&lt;p&gt;
  				&lt;/section&gt;
  
</t>
<t tx="leo.20170116002413.82">				&lt;/section&gt;

@others
				&lt;section&gt;
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;老師給我們的零件網站,透過這一次的作業,我發現非常實用,以後應該還會多多利用那個網站,是個非常方便的網站&lt;p&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170116002413.83">@others
				&lt;section&gt;
					&lt;h2&gt;心得&lt;/h2&gt;
					&lt;p&gt;這一次我們這組整個討論下來,覺得這一次的作業比較複雜一點但,在這一次又有學到新的知識,又得到了一些還沒學過的能力&lt;p&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170116002413.84">(uncached) leo.20161103232832.3
Diff...
+ 				&lt;section&gt;
+ 					&lt;p&gt;作業4&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/CgB678cjUhI" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
  				&lt;/section&gt;
  
</t>
<t tx="leo.20170116002413.85">				&lt;section&gt;
					&lt;p&gt;作業4&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/CgB678cjUhI" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

</t>
<t tx="leo.20170116002413.86">				&lt;/section&gt;

</t>
<t tx="leo.20170116002413.87">(uncached) leo.20161103233616.1
Diff...
+ 					&lt;p&gt;作業5&lt;/p&gt;
  @others
+ 				&lt;/section&gt;
</t>
<t tx="leo.20170116002413.88">					&lt;p&gt;作業5&lt;/p&gt;
@others
				&lt;/section&gt;
</t>
<t tx="leo.20170116002413.89">@others
</t>
<t tx="leo.20170116002413.9">(uncached) leo.20161104010025.1
Diff...
   &lt;/p&gt;
  				&lt;/section&gt;
  @others
  					&lt;h4&gt;作業1&lt;/h4&gt;
- 					&lt;iframe src="https://player.vimeo.com/video/185818182" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                ^ ^^^
+ 					&lt;iframe src="https://player.vimeo.com/video/185824836" width="640" height="400" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
? 					                                                ^^ ^^
  			
                                &lt;/section&gt;
  				
</t>
<t tx="leo.20170116002413.90">(uncached) leo.20161104011701.1
Diff...
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/SWmuThwltWo" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				&lt;/section&gt;
  @others
+ 					&lt;p&gt;作業5&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Vj1Pi6R-Xus" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
+ 				&lt;/section&gt;
+ 
+ 				&lt;section&gt;
</t>
<t tx="leo.20170116002413.91">					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/SWmuThwltWo" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;
@others
					&lt;p&gt;作業5&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/Vj1Pi6R-Xus" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
				&lt;/section&gt;

				&lt;section&gt;
</t>
<t tx="leo.20170116002413.92">@others
</t>
<t tx="leo.20170116002413.93">(uncached) leo.20161104011701.2
Diff...
+ 
+ 				&lt;section&gt;
</t>
<t tx="leo.20170116002413.94">
				&lt;section&gt;
</t>
<t tx="leo.20170116002413.95"></t>
<t tx="leo.20170116002413.96">(uncached) leo.20161103233616.2
Diff...
+ 					&lt;p&gt;作業5&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ZZ8DBt7tuYk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
  @others
+ 				&lt;/section&gt;
+ 
+ 				&lt;section&gt;
+ 					&lt;p&gt;作業6&lt;/p&gt;
+ 					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/dktF_l6UY8o" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.97">					&lt;p&gt;作業5&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/ZZ8DBt7tuYk" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
@others
				&lt;/section&gt;

				&lt;section&gt;
					&lt;p&gt;作業6&lt;/p&gt;
					&lt;iframe width="560" height="315" src="https://www.youtube.com/embed/dktF_l6UY8o" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20170116002413.98">@others
</t>
<t tx="leo.20170116002413.99">(uncached) leo.20161103233616.3
Diff...
+ 				&lt;/section&gt;
+ 
+ 				&lt;section&gt;
+ 					&lt;h2&gt;心得&lt;/h2&gt;
+ 					&lt;p&gt;在改尺寸時遇到了一點麻煩,我們在討論是每一個草圖都要改,還是只要去改最外面的輪廓就好,這次作業很有挑戰&lt;p&gt;
</t>
</tnodes>
</leo_file>
